### PR TITLE
RFC: nested DTO class example

### PR DESCRIPTION
**Pull request by keradus**
I'm not convinced there is value to create standalone class for DTO used only internally within single fixer.

Happy to hear your voice.
also with potential filepath if we want to keep it extracted :D

(ps autoreview will crash, as we explicitly prevent this now, I'm also using too new PHP syntax, but it's only RFC)

### CODE REVIEW

**Comment by Wirone** [comment]
I also thought about a similar approach, but decided against it in the end. It does not make sense to define classes for single-file usage. Instead, I would recommend extending our domain code area - more reusable services, more DTOs, and DI on top of that 😉.

**Comment by julienfalque** [comment]
Agreed. IMO custom PHPStan types using arrays are fine for this usage.

**Comment by Wirone** [comment]
As I [wrote in this thread](https://twitter.com/_Codito_/status/1729845988645339178), personally I treat PHPStan as first-class citizen of the code and that's why I don't have any problem with using array shapes and generics on SA level. I agree that regular classes would be better, but only if created properly. I believe we should work on how our fixers are written - stop reinventing the wheel again ang again, but instead re-use SRP services that operate on clear contracts for input/output data. Until we introduce such approach (analyzers are almost there) we can use array shapes and PHPStan type aliases to define local contracts within single fixers.

**Comment by keradus** [comment]
let's ignore for internal DTOs, I believe will make value for reusable analysers

**Pull request closed without merging**
