### PR TITLE
fix: `ConstantCaseFixer` - do not change class constant usages

### PR DESCRIPTION
**Pull request by kubawerlos**

### CODE REVIEW

**Comment by mvorisek** [comment]
LGTM and thank you, previously there was `T_PAAMAYIM_NEKUDOTAYIM` which is equivalent.

**Comment by kubawerlos** [comment]
> there was `T_PAAMAYIM_NEKUDOTAYIM` which is equivalent.

it's an alias (https://3v4l.org/Wdk51), so I went with the original one.

**Comment by rimas-kudelis** [comment]
Any plans to release this fix?

**Review by Wirone — APPROVED** [review]

**Comment by Wirone** [comment]
> Any plans to release this fix?

It will be available in the next version, which will be released... when it's released 😅.

**Pull request merged**
