### PR TITLE
deps: dev-tools lock bump

### PR DESCRIPTION
**Pull request by keradus**
when i composer-update on dev-tools, i get those updates in lock file. lot of them were removed in #8255 .

any hints, @kubawerlos ? should they be gone or recovered? if gone, what to do to not re-add it on my side?

### CODE REVIEW

**Comment by kubawerlos** [comment]
> when i composer-update on dev-tools, i get those updates in lock file. lot of them were removed in #8255 .

Oh, I have [`kubawerlos/composer-smaller-lock`](https://github.com/kubawerlos/composer-smaller-lock) installed globally, but I was not expecting it to plug in, since it is not allowed in `composer.json` > `config.allow-plugins`.

> should they be gone or recovered?

hard to tell, I've created the plugin, so changes in `composer.lock` are reviewable, but with our adding/removing all those lines we proved that we don't pay attention to `composer.lock` anyway.

**Comment by keradus** [comment]
well, i noticed the change in lock file, so someone noticed it ;)

I suggest we either keep "vanilla" lock file (no plugin-modified, this PR), or we enable the plugin for repo for everyone (i guess per-project dependency).

----------

> since it is not allowed in composer.json > config.allow-plugins.

i would encourage to investigate separately

**Comment by kubawerlos** [comment]
> i guess per-project dependency

I don't get what you mean by that. When the plugin is installed and enabled it simply makes `composer.lock` smaller for all the dependencies that are installed.

**Comment by keradus** [comment]
i meant it to work even if no plugin installed globally

**Comment by keradus** [comment]
replaced by #8263

**Pull request closed without merging**
