### PR TITLE
DX: replace Prophecy with anonymous classes in FileFilterIteratorTest

### PR DESCRIPTION
**Pull request by kubawerlos**

### CODE REVIEW

**Comment by keradus** [comment]
should we put title-based category to `test` ?

**Comment by kubawerlos** [comment]
> should we put title-based category to `test` / `chore` ?

Not sure, 2 of the series already went merged with `DX`

**Comment by Wirone** [comment]
IMHO it's somewhere between DX and chore. Btw. Personally I would prefer one large PR with the same "remove Prophecy" scope rather than multiple smaller ones, to not review same/similar things multiple times 😉. Yeah, "remove Prophecy" is SRP-compliant even if it touches multiple different files.

**Comment by kubawerlos** [comment]
I can make the rest of the changes in a single PR if that would be easier to review, for me it is always easier to review smaller PRs 🤷🏼‍♂️

**Comment by keradus** [comment]
you can even combine existing PRs to single one ;)

**Comment by kubawerlos** [comment]
Replaced by https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/pull/7509

**Pull request closed without merging**
