### PR TITLE
feat: Symfony.trailing_comma_in_multiline - adjust configuration

### PR DESCRIPTION
**Pull request by keradus**
haha, another case how to handle config configuration that is dependent on PHP version

### CODE REVIEW

**Review by SpacePossum — APPROVED** [review]

**Review by SpacePossum — CHANGES_REQUESTED** [review]
New option has been added so this PR might need updating.
Maybe:
```
            'trailing_comma_in_multiline' => [
                'after_heredoc' => true,
                'elements' => [ // explicitly omit 'arguments'
                    'array_destructuring',
                    'arrays',
                    'match',
                    'parameters',
                ],
            ],
```

**Comment by keradus** [comment]
thanks @SpacePossum 

for `after_heredoc`, moving to separated PR: #8188

**Comment by spawnia** [comment]
Are we supposed to run php-cs-fixer on the minimum supported PHP version in a project? What am I supposed to do for a library that still supports PHP 7.4, but my local installation of PHP is 8.3?

**Comment by kubawerlos** [comment]
@spawnia if your library still supports PHP 7.4, as PHP CS Fixer itself, you need to go with only PHP 7.4 options, as PHP CS Fixer itself does: https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/blob/v3.64.0/src/RuleSet/Sets/PhpCsFixerSet.php#L123

**Comment by spawnia** [comment]
I see, so there is no version detection magic going on. We are extending the Symfony config, which explains why this change broke our project. Thank you for the response.

**Comment by kubawerlos** [comment]
No, there is no such detection, might happen in the future, there is a discussion about this: https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/discussions/7312.

**Pull request merged**
