### PR TITLE
bug: Align all the arrows inside the same array

### PR DESCRIPTION
**Pull request by VincentLanglet**
Close https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/4395 
Close https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/5546

With my recent contributions (https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/6559, https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/6515, https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/6450, https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/6445, https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/6444), I really improved the way binary operator are of different "scope" use different placeholder.

For instance
```php
$a = 1; // PLACEHOLDER_=_1
$b = 2; // PLACEHOLDER_=_1

if ($c = 3) { // PLACEHOLDER_=_2
    $d = [ // PLACEHOLDER_=_3
        1 => 1, // PLACEHOLDER_=>_1
        2 => 2, // PLACEHOLDER_=>_1
        // Comment
        33 => 3, // PLACEHOLDER_=>_1
        4 => [ // PLACEHOLDER_=>_1
            1 => 1, // PLACEHOLDER_=>_2
        ];
        44 => [ // PLACEHOLDER_=>_1
            1 => 1, // PLACEHOLDER_=>_3
        ];
        5 => 5, // PLACEHOLDER_=>_1
    ];
}

$e = 3; // PLACEHOLDER_=_1
```

So it would be now possible to align the operator of a same scope, even if it's not in the following line.

I never saw someone reporting an issue for
```
$a = 1;
$b = 2;

$cc = 3;
```
not fixed to
```
$a  = 1;
$b  = 2;

$cc = 3;
```
but for `=>` it's kinda different.

I created https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/4395, got some thumbs up, and there is also https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/5546

I see three solutions:
1) Not merging this, and keeping untouched:
```
$a = [
     1 => [
     ],
     111111 => [],
];
```

2) Merging this, and fixing the previous example to
```
$a = [
     1      => [
     ],
     111111 => [],
];
```

3) Creating another option, something like a `align_scoped_single_space`
I think this is the worst solution because
- It would require a align_scoped_single_space and a align_scoped_single_space_minimal
- It may have only sens/be useful for `=>`, since
```
$variable = 1;
// 20 lines of code

$result = 1;
```
fixed to 
```
$variable = 1;
// 20 lines of code

$result   = 1;
```
wasn't requested so far/could be weird.

I'd like to heard your opinion on this if you have time @SpacePossum (cc @julienfalque)

### CODE REVIEW

**Comment by VincentLanglet** [comment]
Friendly ping @julienfalque WDYT about this ?

**Comment by VincentLanglet** [comment]
Do you have time to take a look @keradus @julienfalque ?

**Comment by VincentLanglet** [comment]
Friendly ping, if you have time to review this @julienfalque :)

**Comment by VincentLanglet** [comment]
Friendly ping,
Do you have tome to review this bugfix @julienfalque @keradus ?

**Review by julienfalque — APPROVED** [review]

**Comment by julienfalque** [comment]
Thank you @VincentLanglet.

**Comment by Gavrisimo** [comment]
Is it possible to revert this change? See this issue for details: https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/issues/6716

**Pull request merged**
