### PR TITLE
fix: `FullyQualifiedStrictTypesFixer` - do not change case of the symbol when there's name collision between imported class and imported function

### PR DESCRIPTION
**Pull request by kubawerlos**
Fixes https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/issues/7744

### CODE REVIEW

**Review by Wirone — APPROVED** [review]
It's a great quick fix ❤️. Currently the fixer handles only places in the code where class-like symbols are used, so basically we don't need imported functions. Later, in #7704 or #7705 we will provide proper support for import kinds.

**Comment by Wirone** [comment]
Thank you very much @kubawerlos 🍻!

**Comment by MidnightDesign** [comment]
@Wirone Is this planned to be released soon? Since PHP CS Fixer doesn't have a way to suppress issues inline (I just found one that was closed as "not planned"), this is breaking our application in CI.

**Comment by Wirone** [comment]
@MidnightDesign unfortunately I can't make release myself and we're waiting for #7752 (or #7719). I believe @keradus will release patch today, but can't tell when exactly. When it comes to CI, I believe you shouldn't allow latest version blindly, but instead you should control which version of the tool is installed (so you can freeze version if there is any problem with new release) 🙂.

**Pull request merged**
