### PR TITLE
bug: PhpUnitMockShortWillReturnFixer - fix for trailing commas

### PR DESCRIPTION
**Pull request by kubawerlos**
Fixes https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/issues/6896

### CODE REVIEW

**Review by Wirone — CHANGES_REQUESTED** [review]
Can we add test case with `willReturnCallback()` like on bug report? Maybe it does not matter that much, but would be good to see it passing.

**Comment by kubawerlos** [comment]
@Wirone we can't because that one is fine for `PhpUnitMockShortWillReturnFixer`, the problem happens with `trailing_comma_in_multiline` adds trailing commas earlier.

**Comment by Wirone** [comment]
@kubawerlos so maybe integration test that would simulate this?

**Review by Wirone — APPROVED** [review]

**Comment by Wirone** [comment]
Thank you, @kubawerlos 🍻

**Comment by vudaltsov** [comment]
Thank you!

**Pull request merged**
