### PR TITLE
feat(NumericLiteralCaseFixer): Introduction

### PR DESCRIPTION
**Pull request by SpacePossum**
replaces https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/pull/7082

### CODE REVIEW

**Comment by SpacePossum** [comment]
Open questions:
- should fixing `T_DNUMBER` be opt-in (as the deprecated rule didn't touch these)?
- should `T_DNUMBER` be fixed to upper or lower case?

Example usage of `T_DNUMBER` with `(e|E)` in it; Symfony `src` 12 times upper `E` , 23 times lower `e`

**Comment by SpacePossum** [comment]
rebased on latest and squashed, no other changes

**Comment by Wirone** [comment]
It was open for so long when all maintainers were on vacation, and when we reactivate you're closing all the PRs 😅? I was going to review it soon, maybe even today's evening (tomorrow's a holiday 🌴).

**Comment by SpacePossum** [comment]
this has nothing to do with vacations or holidays so your comment is really off topic IMHO

**Pull request closed without merging**
