### PR TITLE
feature: Trailing Comma In Single Line Array

### PR DESCRIPTION
**Pull request by nelsonsun**

### CODE REVIEW

**Comment by Wirone** [comment]
Hi @nelsonsun, thank you for your contribution! We currently have fixer that does totally opposite thing (`NoTrailingCommaInSinglelineFixer`), so we need @keradus' decision if we also want to have this one.

Anyway, to properly process this PR you should:
- write test cases and push branch only with them, to see CI failure
- after that, provide commit(s) with implementation to see pipeline green
- provide PR description to describe the intention (nice to have)
- fix static analysis problems (you can run PHPStan locally before pushing)

Thanks in advance!

**Comment by nelsonsun** [comment]
> Hi @nelsonsun, thank you for your contribution! We currently have fixer that does totally opposite thing (`NoTrailingCommaInSinglelineFixer`), so we need @keradus' decision if we also want to have this one.
> 
> Anyway, to properly process this PR you should:
> 
>     * write test cases and push branch only with them (and maybe empty fixer), to see CI failure _only for fixers'_ cases (every other test must succeed)
> 
>     * after that, provide commit(s) with implementation to see pipeline green
> 
>     * provide PR description to describe the intention (nice to have)
> 
>     * fix static analysis problems (you can run PHPStan locally before pushing)
> 
> 
> Thanks in advance!

ok, I will write a test for this and fix the ci problem when I have time

**Comment by kubawerlos** [comment]
@nelsonsun is there any PHP community using this as part of its coding standards or does it bring some benefit having trailing commas in single-line arrays?

**Comment by Wirone** [comment]
> ok, I will write a test for this and fix the ci problem when I have time

@nelsonsun let us know if you plan to work on this. It's been 2 weeks now without proper tests, if nothing changes I'll just close it to reduce amount of opened PRs. For now I'm going to convert PR into draft.

**Pull request closed without merging**
