### PR TITLE
feat: Rename `CurlyBraceTransformer` to `BraceTransformer`

### PR DESCRIPTION
**Pull request by localheinz**
This pull request

- [x] renames the (internal) `CurlyBraceTransformer` to `BraceTransformer`

Related to https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/pull/5915#issuecomment-974674378.
Follows https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/issues/7328#issuecomment-1736909937.

💁‍♂️ Looks like it's not used anywhere, maybe we should remove or use it where it makes sense?

### CODE REVIEW

**Comment by Wirone** [comment]
> Looks like it's not used anywhere, maybe we should remove or use it where it makes sense?

All transformers are magically registered in `PhpCsFixer\Tokenizer\Transformers::registerBuiltInTransformers()`  and used effectively in `PhpCsFixer\Tokenizer\Tokens::applyTransformers()` during tokenisation, so we can't remove it 😉.

PS. I would wait with such refactorings until we set up final vision in #5915 (especially [here](https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/pull/5915#discussion_r1338403369)).

**Comment by Wirone** [comment]
> The transformers refer to PHP tokens, and the constants sometimes use inconsistent naming, too.

@localheinz I've already [warned you about that](https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/pull/7333#issuecomment-1737252377) in your first PR that touched tranaformers 😉. Some fixers can be renamed safely IMHO, but we really need some decisions in #5915.

**Comment by keradus** [comment]
If I miss sth please describe.
As long as we rename internal class, but not exposed CT:: values, we are good to rename things.

If we would rename CT::*, we can break BC.

**Review by keradus — APPROVED** [review]

**Comment by localheinz** [comment]
Thank you, @keradus and @Wirone!

**Pull request merged**
