### PR TITLE
CI: Introduce `composer-unused`

### PR DESCRIPTION
**Pull request by Wirone**
This tool verifies if `composer.json` contains dependencies that are not used in the code, so it's possible to find packages that can be removed.

### CODE REVIEW

**Comment by Wirone** [comment]
I wanted to handle `composer/xdebug-handler` with custom config:

```php
<?php

declare(strict_types=1);

use ComposerUnused\ComposerUnused\Configuration\Configuration;

return static function (Configuration $config): Configuration {
    $config
        ->setAdditionalFilesFor('composer/xdebug-handler', [
            __DIR__.'/../php-cs-fixer',
        ])
    ;

    return $config;
};
```

but it fails:

```
Fatal error: Uncaught Error: Call to undefined method PhpParser\Node\Expr\Closure::getParts() in dev-tools/vendor/composer-unused/symbol-parser/src/Parser/PHP/DefinedSymbolCollector.php:65
Stack trace:
#0 dev-tools/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(200): ComposerUnused\SymbolParser\Parser\PHP\DefinedSymbolCollector->enterNode(Object(PhpParser\Node\Stmt\Expression))
#1 dev-tools/vendor/nikic/php-parser/lib/PhpParser/NodeTraverser.php(91): PhpParser\NodeTraverser->traverseArray(Array)
#2 dev-tools/vendor/composer-unused/symbol-parser/src/Parser/PHP/SymbolNameParser.php(55): PhpParser\NodeTraverser->traverse(Array)
#3 dev-tools/vendor/composer-unused/symbol-parser/src/Symbol/Provider/FileSymbolProvider.php(44): ComposerUnused\SymbolParser\Parser\PHP\SymbolNameParser->parseSymbolNames('#!/usr/bin/env ...')
#4 dev-tools/vendor/composer-unused/symbol-parser/src/Symbol/Loader/FileSymbolLoader.php(70): ComposerUnused\SymbolParser\Symbol\Provider\FileSymbolProvider->provide()
#5 dev-tools/vendor/composer-unused/symbol-parser/src/Symbol/Loader/CompositeSymbolLoader.php(29): ComposerUnused\SymbolParser\Symbol\Loader\FileSymbolLoader->load(Object(ComposerUnused\ComposerUnused\Composer\Package))
#6 [internal function]: ComposerUnused\SymbolParser\Symbol\Loader\CompositeSymbolLoader->load(Object(ComposerUnused\ComposerUnused\Composer\Package))
#7 dev-tools/vendor/composer-unused/symbol-parser/src/Symbol/SymbolList.php(23): iterator_to_array(Object(Generator))
#8 dev-tools/vendor/icanhazstring/composer-unused/src/Command/Handler/CollectRequiredDependenciesCommandHandler.php(60): ComposerUnused\SymbolParser\Symbol\SymbolList->addAll(Object(Generator))
#9 dev-tools/vendor/icanhazstring/composer-unused/src/Console/Command/UnusedCommand.php(182): ComposerUnused\ComposerUnused\Command\Handler\CollectRequiredDependenciesCommandHandler->collect(Object(ComposerUnused\ComposerUnused\Command\LoadRequiredDependenciesCommand))
#10 dev-tools/vendor/symfony/console/Command/Command.php(326): ComposerUnused\ComposerUnused\Console\Command\UnusedCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#11 dev-tools/vendor/symfony/console/Application.php(1078): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#12 dev-tools/vendor/symfony/console/Application.php(324): Symfony\Component\Console\Application->doRunCommand(Object(ComposerUnused\ComposerUnused\Console\Command\UnusedCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#13 dev-tools/vendor/symfony/console/Application.php(175): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#14 dev-tools/vendor/icanhazstring/composer-unused/bin/composer-unused(66): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput))
#15 dev-tools/vendor/icanhazstring/composer-unused/bin/composer-unused(67): {closure}(Array)
#16 dev-tools/vendor/bin/composer-unused(119): include('/Volumes/Projec...')
#17 {main}
  thrown in dev-tools/vendor/composer-unused/symbol-parser/src/Parser/PHP/DefinedSymbolCollector.php on line 65
```

So in the end I just excluded this package.

CC: @icanhazstring

**Comment by icanhazstring** [comment]
Nice catch. Would You be so kind to create a quick issue in https://github.com/composer-unused/symbol-parser

I will take a look 🙂

**Comment by Wirone** [comment]
Currently AFK and 🚘, so maybe later or manage it by yourself if it's not a problem 🙂.

**Comment by icanhazstring** [comment]
Also abroad. 😅
Let's see who gets to it first 🙂

**Review by keradus — APPROVED** [review]

**Comment by kubawerlos** [comment]
Thank you @Wirone

**Pull request merged**
