### PR TITLE
DX: `NumericLiteralSeparatorFixer` - change default strategy to `use_separator`

### PR DESCRIPTION
**Pull request by keradus**
PHP introduced the possibility of using a separator.
I understand that not everyone are so-far used to it, but the rule that is numeric_separator should by default add separator, not remove it. I'm OK with strategy to remove it on custom demand.
With that, I'm updating the default config.

If someone is not convinced to use the separator, they will simply _NOT_ enable the rule.
But if someone want to use separator, finding Fixer rule for it and then... have separators forbidden by default, it is confusing.

Compare it with typed properties, new PHP introduces typed properties and rule for them by default would... prevent the usage? nah...

ref:
- https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/pull/7713#issue-2075141590
- https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/pull/6761/files#r1447922649
- https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/pull/6761#discussion_r1214414232

If conclusion here would take time, I'm eager to mark the rule itself as "experimental" till we have the conclusion - #7731 - to avoid complexity of changing default config only with next MAJOR release.

### CODE REVIEW

**Comment by keradus** [comment]
@Wirone I fail to see your point, I will use argument you used in discussion on previous rule - if not interested in using the rule, don't use it. Just pushing 👎🏻 is not constructive.

**Comment by Wirone** [comment]
[It was already concluded](https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/pull/6761#discussion_r1447947355), why are you pushing again for this? I don't get it, but you do you. I am against the change, said several times already that for me the default is _no separator_.

**Comment by keradus** [comment]
myself and original rule creator is for the config I propose in this PR.
I would like Fixer to promote features from new PHP versions, not the previous variants, by default.

Do you really plan to use the rule if you are against it ?

**Comment by keradus** [comment]
argument about name - I can live with it, tho we would really benefit from a unified naming approach (maybe one day)

argument about usage - so that's the thing, as feature that was not possible before, adoption may not be wide. Tooling automating the usage could help with that.
RFC voting was [33:11](https://wiki.php.net/rfc/numeric_literal_separator)

**Comment by Wirone** [comment]
It's not about promoting new features blindly, it's about sane standards. You always ask in issues/PRs "is this a part of a widely used standard?", maybe ask here? I don't see it mentioned in PER-CS. If PHP introduces a way to natively unfinalise in some circumstances, will you promote it just because it's new?

As I said, I believe it's not widely used so making it as default does not make sense. It was introduced in 7.4 four years ago, if people really liked it, the adoption would be higher. So maybe the fact it's not commonly used does not come from unfamiliarity, but from conscious decision?

**Comment by keradus** [comment]
> It's not about promoting new features blindly, it's about sane standards.

I do not believe it's "blindly":
> RFC voting was [33:11](https://wiki.php.net/rfc/numeric_literal_separator) (it's also established standard for using _ separator for typescript, python, rust, maybe more)

>  but from conscious decision?

or lack of much cases when we use numbers over 999 in repos 😅 



I think we are fixed on our opinion. happy to hear more voices.

**Comment by Wirone** [comment]
Why do you refer to RFC votes? People were voting on adding feature to the language, not about using it 🤷‍♂️. [Here are numbers](https://twitter.com/faguo/status/1746774589991010763):

> Exakat sees it in 5.44% (168 projects out of 3087). 
>
> Largest user is Psalm, with 160 occurrences. Almost all of the integers > 1000 are in that format. Most others have a few occurrences.
>
> symfony, laravel, laminas (and plugins) have occurrences; not Wordpress.

I believe you're biased by your company's projects, and the fact _you_ use this format does not mean it's common 😉.

**Comment by julienfalque** [comment]
To be honest I tend to agree with @keradus. The current *de facto* standard is likely "we don't know about this feature or don't really think about using it when a use case occurs", This is different from "we don't like this feature and refuse to use it in our codebase" and is best represented by not enabling the rule at all.

IMO, the right places to make an opinionated choice for this rule are rulesets and users configs.

**Comment by VincentLanglet** [comment]
Seems natural that the rule use `_` by default. If you don't want/use this syntax, you don't use this rule.

Rector consider the `_` as the default too https://github.com/rectorphp/rector/blob/main/docs/rector_rules_overview.md#addliteralseparatortonumberrector

**Comment by Wirone** [comment]
FYI: I run [a poll on Twitter](https://twitter.com/_Codito_/status/1746668024722051208), the results _now_ are slightly in favour of using separators. 

---

Thanks @VincentLanglet for the Rector context and your opinion in general. It sheds some new light for me, but I'm still not fully convinced. Thanks @julienfalque too.

> The current de facto standard is likely "we don't know about this feature or don't really think about using it when a use case occurs", This is different from "we don't like this feature and refuse to use it in our codebase" and is best represented by not enabling the rule at all.

IMHO It's impossible to determine why the [adoption is so low](https://twitter.com/faguo/status/1746774589991010763). It may be because unfamiliarity, "whatever" approach, but may be because of usage refusal. I asked in other places too, and I have for example such feedback from @Ocramius:

> I don't use the numeric separator at all: reads awkward, and we got enough trouble with locales to add even more "developer -oriented" locales 😬

There's also opinions like [this one](https://marc.info/?l=php-internals&m=145320709922246&w=2) from the time when RFC was processed, but here's feedback from _today_: 

> I use it from time to time and think it improves readability. But to me that's a developer's opt-in to the feature.

I kind of agree that using separator by default would be more natural when it comes to enabling rule in the config, **but** it does not match with current real-world usage and I am not sure we should promote this. I also see potential scenarios where codebase has _some_ literals _with_ separators, but most of them are _without_ them and in that case it would be natural to standardise the usage to use `no_separator` 🤷‍♂️. Yes, it may be configured to do so, but I still think that default config should represent the established PHP trend, which is... not using separator 😅.

Anyway, if we're going to mark this as experimental, we can also collect the feedback from the users, however I am not completely sure if anyone will come here to share the opinion 😉.

**Comment by Wirone** [comment]
> I kind of agree that using separator by default would be more natural when it comes to enabling rule in the config, but it does not match with current real-world usage and I am not sure we should promote this.

Re-thinking my own opinion and have mixed feelings. On the one hand I think you guys are right and using separator would be more natural default _when enabling the rule in users' own config_, but on the other hand real-world usage seem to be different. Maybe we should establish general approach for it, but it seems like it should be:

- the most natural default config on the rule level (so enabling it would lead to expected behaviour)
- community-specific config should be on the ruleset (or project config's) level, to achieve what's expected

In this case probably using separator by default is OK on rule level as you mentioned, without including it in any PSR/PER ruleset (since it's not covered there). At this point I'm think I'm +0 about this 😅.

**Comment by keradus** [comment]
I agree we should not include it in any ruleset to start adding `_` unless given community (eg PSR) start recommending it.

**Comment by Wirone** [comment]
> I agree we should not include it in any ruleset to start adding `_` unless given community (eg PSR) start recommending it officially.

Not only add, rulesets should not also _remove_ the separator unexpectedly, unless it's a part of that standard.

**Review by Wirone — APPROVED** [review]

**Pull request merged**
