### PR TITLE
feat: Report used memory to 2 decimal digits only

### PR DESCRIPTION
**Pull request by mvorisek**
Improve UX, this is how memory is usually reported, for ex. in PHPUnit.

### CODE REVIEW

**Review by Wirone — APPROVED** [review]

**Comment by Wirone** [comment]
Thanks @mvorisek 🍻!

**Comment by keradus** [comment]
@Wirone when merging please always validate category.
it's not a new feature

**Comment by mvorisek** [comment]
Is there any PHP CS Fixer dev docs for that somewhere?

**Comment by Wirone** [comment]
There's `.github/prlint.json` that lists supported categories, PR should use the most appropriate one. Feature should be used only if PR actually introduces something new 🙂.

**Comment by mvorisek** [comment]
I know and sorry about this. Dev docs for that would be welcomed as what is chore, DX, ...

**Comment by Wirone** [comment]
Don't feel sorry, I should have caught it before merging 🙂.

**Comment by keradus** [comment]
feature vs bug also documented here: https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/blob/master/feature-or-bug.rst

but overall, even if not documented, this PR is good, simply not a feature from user perspective ;)

**Pull request merged**
