### PR TITLE
DX: Use relative fixture path as integration test case's name

### PR DESCRIPTION
**Pull request by Wirone**
Before:

image

After:

image

### CODE REVIEW

**Comment by SpacePossum** [comment]
I made the full path so it is easier to copy-paste it to find the file, so I'm not in favor of this change.

**Comment by Wirone** [comment]
I don't really see any use case where full path would be helpful and actually needed. Short path like here is sufficient, longest form that should be printed is relative path from the root of the project IMHO 🙂.

**Comment by SpacePossum** [comment]
> relative path from the root of the project 

sounds like a good compromise :+1:

**Comment by Wirone** [comment]
Changed the path to be relative to project's root dir. `vendor/bin/phpunit --testdox tests/IntegrationTest.php`:

image

**Review by SpacePossum — APPROVED** [review]

**Pull request merged**
