### PR TITLE
bug: Fix indentation of comment on switch case

### PR DESCRIPTION
**Pull request by julienfalque**
Fixes https://github.com/FriendsOfPHP/PHP-CS-Fixer/issues/6470#issuecomment-1185991718=, #6572 and #7179.

### CODE REVIEW

**Comment by julienfalque** [comment]
This creates a [conflict](https://github.com/FriendsOfPHP/PHP-CS-Fixer/runs/7369775808?check_suite_focus=true#step%3A11%3A517=) with [PSR-12 rule about the `// no break` comment](https://www.php-fig.org/psr/psr-12/#52-switch-case). Should the comment remain indented as part of the case body? Or should it be indented like the following `case`/`default`? Or should we just dismiss this PR?

**Comment by mvorisek** [comment]
> This creates a [conflict](https://github.com/FriendsOfPHP/PHP-CS-Fixer/runs/7369775808?check_suite_focus=true#step%3A11%3A517=) with [PSR-12 rule about the `// no break` comment](https://www.php-fig.org/psr/psr-12/#52-switch-case). Should the comment remain indented as part of the case body? Or should it be indented like the following `case`/`default`? Or should we just dismiss this PR?

There are 3 states of comment indentation:

a) "for case body"
b) "for next case"
c) invalid - not a) or b)

so the fixer should work like following (in order):

a) state is invalid if the next token (excluding other comments) is `case` or `default` and the previous code always terminate - of course, we cannot detect `never` return type from user functions, but we can detect `break`, `return`, `exit`, `throw` statements

c) should be always fixed to a)

when a) state is not valid, fix to b)

some usecases:

```
switch ($foo) {
    case 1:
        // no break - comment for case body
    case 2:
        if ($a > $b) {
            return '1 or 2';
        }
        // no break - comment for case body
    case 3:
    // comment for next case
    case 4:
        if ($a > $b) {
            return '1 or 2';
        }
    // comment for next case
    case 5:
    case 6:
        // no break - comment for case body
    // comment for next case
    default:
        return '2 or default';
}
```

**Comment by julienfalque** [comment]
Thinking about this again. Currently this is supported for `else`/`elseif` blocks but only to make tests from `braces` pass. I think there is no reliable way to say whether a comment is intended to be part of the body of its block or if it's related to the next one. See #5115 for an exemple where a comment before a `else` is intended to be part of the `if` body but considered to be related to the `elseif`.

Instead of extending this hazardous behavior to `case`/`default`, I propose to drop it entirely except in `braces` for BC.

**Comment by mvorisek** [comment]
Yes,

if comment is not the last statement/token or if it is inside curly braces (where it is always part of the body block),

then simply both levels of comment indentation can be allowed/unfixed + zero indentation for comments. If different, it should still be fixed as if it was part of the body block.

**Comment by julienfalque** [comment]
@SpacePossum @keradus @kubawerlos What is your opinion about this?

**Comment by keradus** [comment]
@SpacePossum and myself on holidays, maybe @kubawerlos or @localheinz ?

**Comment by TeLiXj** [comment]
hi! any update on this?

**Comment by leofeyer** [comment]
> I think there is no reliable way to say whether a comment is intended to be part of the body of its block or if it's related to the next one.

IMHO there is, if the comment is preceded by a new line:

```php
switch (true) {
    case 'foo':
        // inner block comment
    case 'bar':
        break;

    // outer block comment
    case 'baz':
        break;
}
```

If there are no empty lines at all, there is no reliable way indeed.

**Comment by leofeyer** [comment]
Also, if the comment comes right after the `break;` statement, I would say it is safe to assume that it is intended for the outer block.

**Comment by Wirone** [comment]
@leofeyer new line before comment can't determine indentation:

```php
switch (true) {
    case 'foo':
        $foo = [];

        // Some complex logic
        foreach ($foo as $f) {
        }

        // Some comment
        break;

    // outer block comment
    case 'baz':
        break;
}
```

But yeah, when comment is after `break;` then it's related to next case.

**Comment by julienfalque** [comment]
#7624 introduced a new option to control this behavior for `else`/`elseif` cases. I'll update this PR to extend this option to `cases`.

**Comment by zerocrates** [comment]
@julienfalque I can't quite tell: did you ever make the updated version of this PR you had mentioned before to add case support to the stick_comment_to_next_continuous_control_statement option?

**Pull request closed without merging**
