### PR TITLE
feature: add at least one space around binary operators

### PR DESCRIPTION
**Pull request by duboism**
This PR refreshes  #6878 which was closed due to a lack of activity (see the discussion there). The goal is to address #6861 (itself linked to #6849).

Most of the work was done by @MrYamous in #6878 (see MrYamous/PHP-CS-Fixer:6861), I just rebased and finished a few things.

### CODE REVIEW

**Comment by duboism** [comment]
Before merging, I'd like to discuss one point: #6861 proposed to add this as the default for the `@PSR12` ruleset as it is designed to be safe (see the discussion at #6849 and #6861). Should I do that here or in another PR ?

**Comment by duboism** [comment]
> > Before merging, I'd like to discuss one point: #6861 proposed to add this as the default for the `@PSR12` ruleset as it is designed to be safe (see the discussion at #6849 and #6861). Should I do that here or in another PR ?
> 
> I have noticed that this is already stated in the doc (added by @MrYamous in [4d5a019](https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/commit/4d5a0194dfd697f9ec77c52419d325b559354813)). AFAIU, it's not done in the code.

Is this enough to add `at_least_single_space` in ` @PSR12` rulset:
```diff
$ git diff
diff --git a/src/RuleSet/Sets/PSR12Set.php b/src/RuleSet/Sets/PSR12Set.php
index b549ca3ee..659e274f0 100644
--- a/src/RuleSet/Sets/PSR12Set.php
+++ b/src/RuleSet/Sets/PSR12Set.php
@@ -25,6 +25,9 @@ public function getRules(): array
     {
         return [
             '@PSR2' => true,
+            'binary_operator_spaces' => [
+                'default' => 'at_least_single_space',
+            ],
             'blank_line_after_opening_tag' => true,
             'blank_line_between_import_groups' => true,
             'blank_lines_before_namespace' => true,
```
?

**Comment by kubawerlos** [comment]
Looks reasonable, @duboism can you rebase?

**Comment by Wirone** [comment]
@duboism you need to run `composer docs` after modifying ruleset 🙂.

**Comment by duboism** [comment]
> @duboism you need to run `composer docs` after modifying ruleset slightly_smiling_face.

Arf, I tried but it failed for some mysterious reasons so I was hoping that this was not needed. I will retry that.

**Comment by duboism** [comment]
I think it's OK this time: I was able to run `composer docs` (Fedora 37 comes with PHP 8.1 and it turns out that running docker on Fedora is harder than it looks but [Remi's RPM repository](https://blog.remirepo.net/) came to help to install PHP 8.2) and all tests are green.

**Review by kubawerlos — APPROVED** [review]

**Comment by SpacePossum** [comment]
There is an option to ensure a single space and one to align the operators and the obvious one of not use this fixer at (so not enforce single space and not enforce alignment),
which practical scenario does this new option allow for that is not covered by the existing 3?

**Comment by Wirone** [comment]
@SpacePossum it's described in #6861 and discussed before in #6849.

**Review by Wirone — APPROVED** [review]

**Comment by Wirone** [comment]
Thank you @duboism and @MrYamous 🍻

**Comment by duboism** [comment]
Thank you for this ! It was interesting to to work on this project: the tooling is great and the community is very active and friendly.

**Pull request merged**
