### PR TITLE
feat: increase `ordered_interfaces` fixer priority

### LINKED ISSUE #7760: Increase priority of the `ordered_interfaces` fixer
#### TL;DR;

I need to increase the priority of the `ordered_interfaces` fixer in order to allow placing another fixer between it and the `ordered_class_elements` fixer.

#### Details

I'm working on the fixer, that will sort methods in the same order, as they are defined in parent classes/interfaces. [Details](https://github.com/erickskrauch/php-cs-fixer-custom-fixers/issues/4). The fixer is implemented, but there is a problem: it sorts methods based on the order of class extensions: `extends` first, then `implements`. `ordered_interfaces` might change the order of those extensions and it will affect my fixer, so I want to run my fixer after `ordered_interfaces`. `ordered_interfaces` doesn't have the `getPriority()` method thus it has priority `0`.

This would be fine if I didn't also want to leave an opportunity for the fixer `ordered_class_elements` to execute AFTER my fixer. The `ordered_class_elements` has priority `65`, which gives me an invariant: my fixer should have priority higher than `65`, but lower than `0`.

So I ask you to increase the priority of the `ordered_interfaces` to `75` or something to leave room to place my fixer in between.

### PR DESCRIPTION
**Pull request by erickskrauch**
Fixes #7760.

### CODE REVIEW

**Comment by erickskrauch** [comment]
In case this PR will be accepted, I feel like there should be a comment which will describe the reason, why this priority is set.

**Comment by keradus** [comment]
@erickskrauch , can you sync master branch into your PR and show how the tests would behave?

**Comment by keradus** [comment]
@erickskrauch , can you fix the failing CI jobs and also sync master branch into your PR?

**Comment by erickskrauch** [comment]
Yes, I can. It seems like I need to write some comments about fixer dependencies, but there are no direct dependencies. This fixer is very basic. So for me, it seems safe to set high priority for it to allow other fixers to be placed after that fixer, but before some others (my [case](https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/issues/7760)).

But since this is your codebase and I'm extremely bad at English, can I ask you to help me draft this commentary so that it is understandable first and foremost to you?

**Comment by erickskrauch** [comment]
@keradus, I can't anymore. Since the changes introduced in the https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/commit/9167592a7eb31f399f61dda24f2a660f3272cf8c commit, the `ordered_interfaces` must have priority `<7`, but for my case I need it to be at least `67`, which is invariant.

If you don't see any possible solution for this situation, I think I will need to close this PR as not implementable at the moment until some graph-based priorities are introduced.

**Comment by keradus** [comment]
The mentioned commit proved priority dependency between 2 fixers that was not explicitly declared before. That not-yet-discovered priority dependencies are the risk I was mentioning for changing any priority.

I see the value in switching to graph solution, but if you would construct the graph with circuit (A->B->C->A), and to what I understand is your challenge, it would not allow us to solve and run fixers in linear order. I'm happy to have a PR one day that is not only moving us to graph, but also solving the circuits.

I'm closing the PR due to discussion.

**Pull request closed without merging**
