### PR TITLE
fix: Revert 5620 and add problematic test cases

### LINKED ISSUE #7620: `fully_qualified_strict_types` breaks @see tag
### Description

`fully_qualified_strict_types` breaks @see tag by AddSeeTestAnnotationRector
https://github.com/rectorphp/rector-phpunit/blob/main/docs/rector_rules_overview.md#addseetestannotationrector

```diff
- * @see \CodeIgniter\Pager\PagerRendererTest
+ * @see PagerRendererTest
```

See also https://github.com/php-fig/fig-standards/blob/master/proposed/phpdoc-tags.md#513-see

### Runtime version

PHP CS Fixer 3.42.0 Three Keys by Fabien Potencier and Dariusz Ruminski.
PHP runtime: 8.2.13

### Used command

php-cs-fixer fix --ansi --verbose --diff

### PR DESCRIPTION
**Pull request by mvorisek**
In a project with `['leading_backslash_in_global_namespace' => true]` config the fixer breaks our code in about every second file.

fix #7620, https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/issues/7620#issuecomment-1868936566, https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/pull/7622#discussion_r1436155496, https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/pull/7622#discussion_r1436155713

---

I prefer to revert the changes until it is too late and then parse & do the changes on `TypeExpression`, phpdocs grammar is simply too complex too handle it using regexes. Also, `@psalm-param` should be fixed the same as `@param` to avoid same file/code inconsistencies. The supported tags should be unified across the whole PHP CS Fixer project

Also, I do no think it is good to land fixers that cannot work on parsed phpdoc, as if landed in "improved gradually fashion", we need to fix CS in many repos again and again.

### CODE REVIEW

**Review by GrahamCampbell — CHANGES_REQUESTED** [review]
This reverts too much stuff IMO. We should just take out the call to `fixPhpDoc` and the `fixPhpDoc` function, and associated tests (just 1 data provider entry, 1 data provider function and its associated test).

**Comment by Wirone** [comment]
I am against reverting all of the changes related to FQCNs. There is already ongoing fix for phpDoc handling, we need to introduce config option to be able to opt-in/opt-out from phpDoc processing, and if there are issues with leading backslash, we just need to fix them too. It does not make sense to revert so many new features, it's not that crucial even if some cases are problematic, because it's not required to update to the new Fixer version instantly. Reverting all of these means a lot of work to be done again and we don't have resources for that.

**Review by Wirone — CHANGES_REQUESTED** [review]
Preventing accidental merge.

**Comment by Wirone** [comment]
I am going to close this PR because there's no need to revert all of the work done around FQCNs. #7622 and #7628 should cover it good enough - processing phpDocs within `fully_qualified_strict_types` can be disabled completely by setting `'phpdoc_tags' => []`, and even if it's enabled the processing is narrowed to simple FQCNs only, so it should not break the code. If there are other problems (like with leading `\` in global namespace) separate issues should be reported so we can fix these.

**Pull request closed without merging**
