### PR TITLE
minor: `SingleSpaceAroundConstructFixer` - support space before `as`

### LINKED ISSUE #5155: foreach declaration SpacingBeforeAs and  SpacingAfterAs expected 1 space after "as"
```diff
--- Original
+++ New
-        foreach ( ([1, 2, 3])as        $key => $item) {
+        foreach (([1, 2, 3]) as $key => $item) {
```

### PR DESCRIPTION
**Pull request by paulbalandan**
Closes #5155

### CODE REVIEW

**Comment by SpacePossum** [comment]
Looking good.
Wondering, as 5155 is about `foreach` , does this fix also touch `<?php use exception   as    bar;`  for example? Do we want to (I think so)? Maybe having some tests for this would be good.

**Review by kubawerlos — APPROVED** [review]
Maybe some tests with meaningful token before `as` like:
```php
foreach (range(0, 9)as$i) { echo $i; }
foreach (range(0, 9)as $i) { echo $i; }
```
but I won't insist on adding them.

**Review by Wirone — APPROVED** [review]

**Comment by Wirone** [comment]
Thank you @paulbalandan 🍻

**Comment by SpacePossum** [comment]
so  does this fix also touch `<?php use exception   as    bar;`  (https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/pull/7029#issuecomment-1578023222) ? Not sure why we are skipping tests here (or reviews)

**Pull request merged**
