### PR TITLE
CI: early compatibility checks with Symfony 7

### PR DESCRIPTION
**Pull request by keradus**

### CODE REVIEW

**Comment by keradus** [comment]
🤷🏻

**Comment by keradus** [comment]
🤷🏻

**Comment by VincentLanglet** [comment]
Since your Ci is running successfully with SF 7, would it be ok to add `|| ^7.0` in the composer.json in order to allow us trying SF 7 on our CI too ? Thanks 🙏

I can do the PR if accepted

cc  @Wirone

**Comment by keradus** [comment]
from semver perspective, 7@beta can still break BC before releasing 7@stable.
is core Symfony team confirming to not introduce any more BC breaks for v7 line? if not, I prefer to wait for stable release.

**Comment by VincentLanglet** [comment]
> is core Symfony team confirming to not introduce any more BC breaks for v7 line? if not, I prefer to wait for stable release.

No idea, I see multiple fixes but I can't guarantee about BC-break indeed.
Maybe @nicolas-greckas can provide an answer for this (?)

**Comment by nicolas-grekas** [comment]
RC1 means no BC breaks anymore so it's safe to allow 7 IMHO

**Comment by VincentLanglet** [comment]
Thanks ; I opened https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/pull/7453 @keradus then.

**Comment by keradus** [comment]
ah, it's already RC? nice!

**Pull request merged**
