### PR TITLE
DX: Drop doctrine/annotations 1, allow doctrine/lexer 3

### PR DESCRIPTION
**Pull request by derrabus**
Follow-up to #6729: This PR migrates the codebase to the new Lexer API and allows the installation of Lexer 3.

### CODE REVIEW

**Comment by keradus** [comment]
@derrabus , fyi

I think I'm ok to keep as-is, unless many folks would complain

https://repo-stats.github.io/

**Comment by keradus** [comment]
Screenshot 2023-02-05 at 00 22 45

**Comment by achterin** [comment]
May I ask why you removed support for doctrine/annotations v1, especially in a patch release? Is it not compatible anymore?

**Comment by derrabus** [comment]
> Is it not compatible anymore?

Exactly.

**Comment by keradus** [comment]
we can support v1+v2 or v2+v3, we prefer the later.
also, SEMVER is not forbidding to bump deps in PATCH release ;)

**Comment by achterin** [comment]
> we can support v1+v2 or v2+v3, we prefer the later. also, SEMVER is not forbidding to bump deps in PATCH release ;)

SEMVER is not forbidding to bump deps, thats right, but you are dropping support for a previously supported version of doctrine/annotations. therefore its a breaking change which should only be done in a major version upgrade.
because of this change one might be stuck on v3.14.2 because another dependency is not yet compatible with doctrine/annotations v2. if there is a fix in a later version of your package, you're out of luck because you can't install it.
anyway, thanks for the explanation.

**Comment by kubawerlos** [comment]
I also thought initially that it counts as BC break, but then I found this: https://semver.org/#what-should-i-do-if-i-update-my-own-dependencies-without-changing-the-public-api

Anyway, @achterin, you can use the [shim](https://github.com/PHP-CS-Fixer/shim) to avoid this and any other future dependencies issues.

**Pull request merged**
