### PR TITLE
DX: temporarily use more than needed extensions

### PR DESCRIPTION
**Pull request by kubawerlos**
Idea of the change was making it easy to revert.

### CODE REVIEW

**Review by Wirone — CHANGES_REQUESTED** [review]
I am against this change, because: "Total duration [18m 40s](https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/actions/runs/5532401221/usage)". It is huge step backwards. I would prefer excluding `tests/Fixtures/Integration/misc/meta_insert_64566_tokens.test` from MacOS check, but unfortunately we don't support OS in `--REQUIREMENTS--` section 😕.

**Comment by kubawerlos** [comment]
So now [those times are NOT random and undeterministic](https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/pull/6954#issuecomment-1553311853)? 😛

macOS is 3 minutes after those changes, so let's try with disabling `none` only for macOS

**Comment by Wirone** [comment]
> So now https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/pull/6954#issuecomment-1553311853? 😛

Who knows, we have only one run, so we can't compare 😛.

**Comment by Wirone** [comment]
Let's try adding `pcntl` extension explicitly, because it looks like ParaUnit does not use parallelisation at all 😕.

**Pull request closed without merging**
