### PR TITLE
fix: Bump React's JSON decoder buffer size

### LINKED ISSUE #8066: Buffer size exceeded exceptions when running in parallel
### Problem description

Having just added php-cs-fixer to a project, and integrated it into our Jenkins CI pipeline, I get the following errors:

```
+ ./vendor/bin/php-cs-fixer check --no-interaction --show-progress=none --diff --using-cache=no -vvv
PHP CS Fixer 3.58.1 7th Gear by Fabien Potencier, Dariusz Ruminski and contributors.
PHP runtime: 8.1.28
Running analysis on 16 cores with 10 files per process.
Parallel runner is an experimental feature and may be unstable, use it at your own risk. Feedback highly appreciated!
Loaded config default from "/var/lib/jenkins/workspace/REDACTED/.php-cs-fixer.php".

In Runner.php line 325:

  [PhpCsFixer\Runner\Parallel\ParallelisationException]
  Buffer size exceeded


Exception trace:
  at /var/lib/jenkins/workspace/REDACTED/vendor/friendsofphp/php-cs-fixer/src/Runner/Runner.php:325
 PhpCsFixer\Runner\Runner::PhpCsFixer\Runner\{closure}() at /var/lib/jenkins/workspace/REDACTED/vendor/friendsofphp/php-cs-fixer/src/Runner/Parallel/Process.php:176
 PhpCsFixer\Runner\Parallel\Process->PhpCsFixer\Runner\Parallel\{closure}() at /var/lib/jenkins/workspace/REDACTED/vendor/evenement/evenement/src/EventEmitterTrait.php:143
 Evenement\EventEmitter->emit() at /var/lib/jenkins/workspace/REDACTED/vendor/clue/ndjson-react/src/Decoder.php:163
 Clue\React\NDJson\Decoder->handleError() at /var/lib/jenkins/workspace/REDACTED/vendor/clue/ndjson-react/src/Decoder.php:143
 Clue\React\NDJson\Decoder->handleData() at /var/lib/jenkins/workspace/REDACTED/vendor/evenement/evenement/src/EventEmitterTrait.php:143
 Evenement\EventEmitter->emit() at /var/lib/jenkins/workspace/REDACTED/vendor/react/stream/src/Util.php:71
 React\Stream\Util::React\Stream\{closure}() at /var/lib/jenkins/workspace/REDACTED/vendor/evenement/evenement/src/EventEmitterTrait.php:143
 Evenement\EventEmitter->emit() at /var/lib/jenkins/workspace/REDACTED/vendor/react/stream/src/DuplexResourceStream.php:196
 React\Stream\DuplexResourceStream->handleData() at /var/lib/jenkins/workspace/REDACTED/vendor/react/event-loop/src/StreamSelectLoop.php:246
 React\EventLoop\StreamSelectLoop->waitForStreamActivity() at /var/lib/jenkins/workspace/REDACTED/vendor/react/event-loop/src/StreamSelectLoop.php:213
 React\EventLoop\StreamSelectLoop->run() at /var/lib/jenkins/workspace/REDACTED/vendor/friendsofphp/php-cs-fixer/src/Runner/Runner.php:349
 PhpCsFixer\Runner\Runner->fixParallel() at /var/lib/jenkins/workspace/REDACTED/vendor/friendsofphp/php-cs-fixer/src/Runner/Runner.php:157
 PhpCsFixer\Runner\Runner->fix() at /var/lib/jenkins/workspace/REDACTED/vendor/friendsofphp/php-cs-fixer/src/Console/Command/FixCommand.php:338
 PhpCsFixer\Console\Command\FixCommand->execute() at /var/lib/jenkins/workspace/REDACTED/vendor/symfony/console/Command/Command.php:326
 Symfony\Component\Console\Command\Command->run() at /var/lib/jenkins/workspace/REDACTED/vendor/symfony/console/Application.php:1078
 Symfony\Component\Console\Application->doRunCommand() at /var/lib/jenkins/workspace/REDACTED/vendor/friendsofphp/php-cs-fixer/src/Console/Application.php:176
 PhpCsFixer\Console\Application->doRunCommand() at /var/lib/jenkins/workspace/REDACTED/vendor/symfony/console/Application.php:324
 Symfony\Component\Console\Application->doRun() at /var/lib/jenkins/workspace/REDACTED/vendor/friendsofphp/php-cs-fixer/src/Console/Application.php:98
 PhpCsFixer\Console\Application->doRun() at /var/lib/jenkins/workspace/REDACTED/vendor/symfony/console/Application.php:175
 Symfony\Component\Console\Application->run() at /var/lib/jenkins/workspace/REDACTED/vendor/friendsofphp/php-cs-fixer/php-cs-fixer:102
 include() at /var/lib/jenkins/workspace/REDACTED/vendor/bin/php-cs-fixer:119

In Decoder.php line 143:

  [OverflowException]
  Buffer size exceeded


Exception trace:
  at /var/lib/jenkins/workspace/REDACTED/vendor/clue/ndjson-react/src/Decoder.php:143
 Clue\React\NDJson\Decoder->handleData() at /var/lib/jenkins/workspace/REDACTED/vendor/evenement/evenement/src/EventEmitterTrait.php:143
 Evenement\EventEmitter->emit() at /var/lib/jenkins/workspace/REDACTED/vendor/react/stream/src/Util.php:71
 React\Stream\Util::React\Stream\{closure}() at /var/lib/jenkins/workspace/REDACTED/vendor/evenement/evenement/src/EventEmitterTrait.php:143
 Evenement\EventEmitter->emit() at /var/lib/jenkins/workspace/REDACTED/vendor/react/stream/src/DuplexResourceStream.php:196
 React\Stream\DuplexResourceStream->handleData() at /var/lib/jenkins/workspace/REDACTED/vendor/react/event-loop/src/StreamSelectLoop.php:246
 React\EventLoop\StreamSelectLoop->waitForStreamActivity() at /var/lib/jenkins/workspace/REDACTED/vendor/react/event-loop/src/StreamSelectLoop.php:213
 React\EventLoop\StreamSelectLoop->run() at /var/lib/jenkins/workspace/REDACTED/vendor/friendsofphp/php-cs-fixer/src/Runner/Runner.php:349
 PhpCsFixer\Runner\Runner->fixParallel() at /var/lib/jenkins/workspace/REDACTED/vendor/friendsofphp/php-cs-fixer/src/Runner/Runner.php:157
 PhpCsFixer\Runner\Runner->fix() at /var/lib/jenkins/workspace/REDACTED/vendor/friendsofphp/php-cs-fixer/src/Console/Command/FixCommand.php:338
 PhpCsFixer\Console\Command\FixCommand->execute() at /var/lib/jenkins/workspace/REDACTED/vendor/symfony/console/Command/Command.php:326
 Symfony\Component\Console\Command\Command->run() at /var/lib/jenkins/workspace/REDACTED/vendor/symfony/console/Application.php:1078
 Symfony\Component\Console\Application->doRunCommand() at /var/lib/jenkins/workspace/REDACTED/vendor/friendsofphp/php-cs-fixer/src/Console/Application.php:176
 PhpCsFixer\Console\Application->doRunCommand() at /var/lib/jenkins/workspace/REDACTED/vendor/symfony/console/Application.php:324
 Symfony\Component\Console\Application->doRun() at /var/lib/jenkins/workspace/REDACTED/vendor/friendsofphp/php-cs-fixer/src/Console/Application.php:98
 PhpCsFixer\Console\Application->doRun() at /var/lib/jenkins/workspace/REDACTED/vendor/symfony/console/Application.php:175
 Symfony\Component\Console\Application->run() at /var/lib/jenkins/workspace/REDACTED/vendor/friendsofphp/php-cs-fixer/php-cs-fixer:102
 include() at /var/lib/jenkins/workspace/REDACTED/vendor/bin/php-cs-fixer:119

check [--path-mode PATH-MODE] [--allow-risky ALLOW-RISKY] [--config CONFIG] [--rules RULES] [--using-cache USING-CACHE] [--cache-file CACHE-FILE] [--diff] [--format FORMAT] [--stop-on-violation] [--show-progress SHOW-PROGRESS] [--sequential] [--] [<path>...]
```

There are a *lot* of files that need fixing, as we've only added the tool to the project and haven't yet run it against all the files to fix them.  So I'm not sure if the above is representative of the fact that there are too many things to report ... or if it's something else going on.

Adding `--sequential` to the command run in CI solves the problem (i.e. I get a big diff of all the fixes that need to be applied).

### Minimal reproducer

Hard to paste a reproducer as the code base is private and large. Our config file is:

```php
<?php

$finder = (new PhpCsFixer\Finder())
    ->in(__DIR__);

return (new PhpCsFixer\Config())
    ->setParallelConfig(PhpCsFixer\Runner\Parallel\ParallelConfigFactory::detect())
    ->setRules([
        '@PER-CS' => true,
        '@PHP82Migration' => true,
        'indentation_type' => true
    ])
    ->setIndent("\t")
    ->setLineEnding("\n")
    ->setFinder($finder);
```

I'm trusting the docs in that I don't need to explicitly exclude the `vendor` directory.

### Fixer version

3.58.1

### PHP version

8.1.28

### How do you run Fixer?

Composer package

### Contribution Checks

- [X] I have verified if this problem was already reported
- [X] I am familiar with ["Feature or bug?"](https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/blob/master/feature-or-bug.rst)

### PR DESCRIPTION
**Pull request by Wirone**
Fixes #8066 (hopefully)

### CODE REVIEW

**Review by keradus — CHANGES_REQUESTED** [review]
I do not believe end-user should be bothered by this buffer size, to be honest. It's tiny implementation detail that I do not want to have as part of config contract.

when the buffer size is used? what is transmitted over it? is it related to how big file will be process, how many files per chunk will be given, how many files per child-process will be there (with all chunks together), ... ?

is there a limit how big the buffer can be? is there a downside of putting buffer size bigger than default? can we hardcode it to big big value, and allow to override by env-var for those 0.00001% use cases that would still require it?

or, maybe we are able to have dynamic buffer size?

**Comment by Wirone** [comment]
@keradus it's size of the buffer in decoder used for transmitting JSONs between main process and workers. The amount of data it must cover depends on size of the single file and fixes applied there, if I get it correctly. We could hardcode bigger value but we will never be sure if it's enough for edge cases like this. [In PHPStan it's configurable](https://github.com/phpstan/phpstan-src/blob/04b840344a5f403e9a48120d7b4dccb278cab2d2/src/Command/WorkerCommand.php#L134) (however undocumented, @ondrejmirtes is it on purpose?) and I knew it from the beginning, but I did not implemented in initially as I hoped that we won't reach the default value 😅. We could utilise env var for this, if you prefer this approach, however I don't think it's significantly better as this would work as a contract too, so what's the problem with having it explicit in the `ParallelConfig`, where it actually belongs?

**Comment by keradus** [comment]
my point is that end-user should not be bothered by buffer size and we should not expect them to configure it in first place. and bothering user by exposing the config to him is suboptimal.

ideally, we never ask user to configure it manually

can we capture the error in code, and handle it? (eg display msg to user how to overcome that issue / env var - or even auto-increase the buffer size)

**Comment by Wirone** [comment]
@keradus I got your point from your first comment, but I am not sure if I agree with it. I believe current default is big enough to handle most of the cases, so people in general are not bothered by this and don't need to configure it. _But_, if they hit this problem, they should be able to control it, and explicit config is better than env var that is magically read and can lead to situations where wrong value is passed there without noticing it.

> can we capture the error in code, and handle it? (eg display msg to user how to overcome that issue / env var - or even auto-increase the buffer size)

Handling is most probably possible, I didn't try. Auto-increase would be rather hard as decoder (which has this in constructor) is created when main process is bootstrapped and is used for binding connections from workers. @clue what do you think about it, is there a way to handle this gracefully, without involving users?

**Comment by clue** [comment]
As a library maintainer I agree that increasing the default buffer size of 64 KiB is reasonable here. As an end user I agree with @keradus that I would very much prefer if sane defaults are applied here and I would never have to worry about any buffer sizes.

The buffer size for the NDJSON decoder (as documented in https://github.com/clue/reactphp-ndjson#decoder) is only the maximum number of bytes to store in memory at once when parsing individual JSON texts to avoid excessive memory usage. It is specifically designed to prevent memory overflows and exhaustion attacks in untrusted environments (think receiving hundreds of streams at once from user input). In a controlled environment, it's fairly common to increase this to a couple of megabytes, as you have more control over how many buffers would be allocated at once. Additionally, the buffer will always be allocated dynamically (it's a string), so if you only ever send a couple of kilobytes per line but have a 1 GiB limit, you will never even get near that value.

I'll leave the decision up to you, but my vote would be to apply a higher default (16 MiB?) after evaluating how many streams you would have (one per parallel worker?) and what kind of data is sent over each stream. Once a higher limit is in place, I don't think a user configurable limit would be asked for anytime soon.

I hope this helps! :+1:

**Review by keradus — APPROVED** [review]
fantastic outcome

**Pull request merged**
