### PR TITLE
Abort call to fix if the file contains `@PhpCsFixerIgnore <name>`

### PR DESCRIPTION
**Pull request by ricardoboss**
Potential fix for #3317

### CODE REVIEW

**Comment by keradus** [comment]
Hey, thanks for raising a PR!

I believe that we should discuss if we want to allow ignoring of violations, and if so - how. Then, solution should be covered with tests

**Comment by ricardoboss** [comment]
True. I wanted to start working on the linked issue, since I really want this feature. I am, however, not proficient enough to implement it in this codebase by myself.

Anyhow, I liked the proposed way to ignore/skip specific fixers with the syntax (`@PhpCsFixerIgnore`) and I would have wanted to apply it only for the next line.

**Review by moon250 — APPROVED** [review]

**Comment by ricardoboss** [comment]
@keradus So, do you want to allow it or not? Would you prefer a different solution? Just checking if this is still a relevant PR.

**Comment by kubawerlos** [comment]
@ricardoboss can you explain why can't you simply exclude such a file(s) in `Finder` in the config?

**Comment by ricardoboss** [comment]
Because then the whole file gets excluded from all fixers. This PR enables you to only exclude the file for one specific fixer. (Or even multiple)

**Comment by MeCapron** [comment]
Hi,

I'm also pushing in favor of this feature.

I have a concrete example : 

We added the rule `no_superfluous_phpdoc_tags` as we do not want to have useless phpdoc in our code base. However, we are using the CMS Magento2 which needs this kind of phpdoc because of its legacy context to perform some reflections (even though the functions are typed).

Excluding the whole file will let us to have a bad formatted file with extra lines or some other troubles because of the exclusion done.

It is really a pain to exclude a complete file only because of one rule in a specific contexts. We need more flexbility.

**Comment by ricardoboss** [comment]
One alternative would be to have multiple config files with different rules for different file globs.

But this is only viable if you have one or two rules you need to adjust.

**Comment by ricardoboss** [comment]
I naturally came across wanting this feature again. I have a class comparing two values and if nothing else works, I want to try using less strict comparison like this:

```php
if (is_a($a, $b)) return $a === $b;

return $a == $b;
```

I want to force strict comparison everywhere else in the codebase, EXCEPT here. I have no way to skip this line or disable the fixer for only this one instance.

Why is it so hard to decide if this feature should be added? Can I help in any other way other than opening this PR?

**Comment by MeCapron** [comment]
Bump.

Can we have a review on this please? I think that it'd be really cool for everyone.

Thanks you

**Comment by kubawerlos** [comment]
@MeCapron do you know what would NOT be really cool? Having any feature without a proper set of test for it 😉

**Comment by ricardoboss** [comment]
@kubawerlos good point. I can look into that later

**Comment by MeCapron** [comment]
> @MeCapron do you know what would NOT be really cool? Having any feature without a proper set of test for it wink

So, when the tests are done you will not mind merging the PR?

If that's the case, I will also take a look at it.

**Comment by keradus** [comment]
I would love to have proper syntax for it aligned. Having `/** asdasdfasdf @PhpCsFixerIgnore braces afdasfdasdf */` in random place of file is not that good.
Imho we should align how to disable multiple rules and where to put it in file - eg only in file header, not as docblock for method param.

it will also help to not traverse whole file content and not analyse each docblock.
also regular comment could be a good option to be used

**Comment by Wirone** [comment]
Closing as this PR does not provide tests and/or is based on opinionated idea, not on discussed proposal. The best place to start such is [RFC section of Discussions](https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/discussions/new?category=rfc), so feel free to open one and provide proposal. Then, after proper solution is chosen, we can proceed to implementation.

**Pull request closed without merging**
