### PR TITLE
feature: add at least one space around binary operators

### PR DESCRIPTION
**Pull request by MrYamous**
For #6861

~~Not exactly finished but main changes about rules is done
Still todo : 
Documentation / Add rule with this new option in PSR-12 set~~

### CODE REVIEW

**Comment by Wirone** [comment]
@MrYamous please make CI green so we can proceed to code review.

**Comment by SpacePossum** [comment]
The ticket states not to fix `$b   = 2; // No fix` , but this PR attempts to do this by making the first space a single one.

Maybe in more general, I'm kind of lost with the request and spec, what is there to be fixed that is not possible through the current configuration options? (as to me the current PR reads as a reimplementation of the option `single_space`)

**Comment by Wirone** [comment]
I am going to close this because:

- CI is not successful
- added [test case](https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/pull/6878/files#diff-1c31d2556c50f33cab028c5b69b65566ebe2ab0365c9fd33f17d2c0776eb9fc2R136) does not make sense, because I would expect that `$b=1` would be changed to `$b = 1` with option "at least one space"
- there was no response from the author for almost a month

@MrYamous Feel free to provide improvements to this PR ans we can reopen it.

**Comment by Wirone** [comment]
@duboism test case added to this PR does not prove it, `$b=1` is not fixed (at least looking at the input and the expected output, they're the same).

**Comment by duboism** [comment]
> @duboism test case added to this PR does not prove it, `$b=1` is not fixed (at least looking at the input and the expected output, they're the same).

I took a look at he code and I think there is an obvious mistake: the method `fixWhiteSpaceAroundOperatorToAtLeastSingleSpace` is introduced but not called. As you pointed out, the test case is wrong but easy to fix (AFAIU, the first argument of the element of the array is the expected value and the second is the input, right ?):

```diff

$ git diff
diff --git a/src/Fixer/Operator/BinaryOperatorSpacesFixer.php b/src/Fixer/Operator/BinaryOperatorSpacesFixer.php
index 4ea852735..58caf09ef 100644
--- a/src/Fixer/Operator/BinaryOperatorSpacesFixer.php
+++ b/src/Fixer/Operator/BinaryOperatorSpacesFixer.php
@@ -419,7 +419,7 @@ private function fixWhiteSpaceAroundOperator(Tokens $tokens, int $index): void
         }
 
         if (self::AT_LEAST_SINGLE_SPACE === $this->operators[$tokenContent]) {
-            $this->fixWhiteSpaceAroundOperatorToSingleSpace($tokens, $index);
+            $this->fixWhiteSpaceAroundOperatorToAtLeastSingleSpace($tokens, $index);
 
             return;
         }
diff --git a/tests/Fixer/Operator/BinaryOperatorSpacesFixerTest.php b/tests/Fixer/Operator/BinaryOperatorSpacesFixerTest.php
index ef11a4e51..482b1a1fe 100644
--- a/tests/Fixer/Operator/BinaryOperatorSpacesFixerTest.php
+++ b/tests/Fixer/Operator/BinaryOperatorSpacesFixerTest.php
@@ -133,7 +133,7 @@ public static function provideConfiguredCases(): array
             ],
             [
                 '<?php $a =  1;
-                $b=2;
+                $b = 2;
                 ',
                 '<?php $a =  1;
                 $b=2;
```

With those modifications, the tests pass.

@MrYamous, could you fix that ?

**Comment by Wirone** [comment]
@duboism you can checkout this branch, rebase, fix it and provide as another PR, we can proceed with tests passing. But please keep original commits so author gets credit for their work.

However, keep in mind that it wasn't reviewed yet, so there might be additional change requests 🙂.

**Comment by duboism** [comment]
OK. I will wait a bit for @MrYamous answer and otherwise I will open a new PR.

**Pull request closed without merging**
