### PR TITLE
feat: UppercaseCaseNameFixer, that makes enum case names uppercase.

### PR DESCRIPTION
**Pull request by voxlz**
As the title describes. I hope I've followed all the contribution guidelines.

### CODE REVIEW

**Comment by voxlz** [comment]
Code is done, but seems like code example fails on older versions of php, since enum is not present in those versions. How am I supposed to configure so that the example code only is present in 8.1? Can't figure it out.

**Comment by Wirone** [comment]
@voxlz you need to use `VersionSpecificCodeSample` in that case.

**Comment by Wirone** [comment]
Something weird happened here 😅. @voxlz was it intentional?

**Comment by voxlz** [comment]
No I think I messed up in git

**Comment by voxlz** [comment]
Did this branch get forgotten? I think I've fixed it on my end weeks ago

**Comment by Wirone** [comment]
@voxlz no, it wasn't forgotten, but there are 40 more PRs and only 3 maintainers, with their own pace of work 🙂. I'm slowly back into Fixer after a busy time during which I couldn't do as much as I would like to. We'll handle it sooner or later 😉.

**Review by Wirone — CHANGES_REQUESTED** [review]
Started review long time ago, but did not finish it 😅. Anyway, looking at it again, and my early feedback is:

- I would rather see this as `enum_case_name_casing` (or similar), with configurable naming strategies
- default one should be PascalCase as in [PER-CS v2](https://www.php-fig.org/per/coding-style/#9-enumerations)

I don't see a point in enforcing only one naming strategy, especially different from the official PHP's standard.

**Comment by Wirone** [comment]
For anyone who would like to pick up this, please take [this feedback](https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/pull/7378#pullrequestreview-1709706945) into consideration. I won't reopen this PR as the author did not address my review for more than a half of the year.

**Pull request closed without merging**
