### PR TITLE
fix: illegal offset type on file-wide return in `ReturnToYieldFromFixer`

### LINKED ISSUE #7217: phpdoc_align changes indentation of some tags
### Description

the `phpdoc_align` rule indents some tags (at least `@param` and `@return`) even though indentation is otherwise handled by `phpdoc_indent`.

Given that there is a specific fixer for indenting, I don't think the alignment fixer should be doing indentation, especially not when it's not consistent across tags.

### Runtime version

```
PHP CS Fixer 3.22.0 (92b019f) Chips & Pizza by Fabien Potencier and Dariusz Ruminski.
PHP runtime: 8.1.21
```

### Used command

`vendor/bin/php-cs-fixer fix`

### Configuration file

```php

return (new PhpCsFixer\Config)
    ->setRiskyAllowed(true)
    ->setRules([
        '@PSR12' => true,
        'array_indentation' => true,
        'blank_line_after_opening_tag' => true,
        'binary_operator_spaces' => [
            'default' => 'single_space',
        ],
        'cast_spaces' => ['space' => 'single'],
        'compact_nullable_typehint' => true,
        'concat_space' => ['spacing' => 'one'],
        'dir_constant' => true,
        'declare_equal_normalize' => ['space' => 'none'],
        'declare_parentheses' => true,
        'type_declaration_spaces' => true,
        'logical_operators' => true,
        'lowercase_cast' => true,
        'lowercase_static_reference' => true,
        'magic_constant_casing' => true,
        'magic_method_casing' => true,
        'method_argument_space' => [
            'on_multiline' => 'ensure_fully_multiline',
        ],
        'method_chaining_indentation' => true,
        'multiline_whitespace_before_semicolons' => true,
        'native_function_casing' => true,
        'native_function_type_declaration_casing' => true,
        'new_with_braces' => true,
        'no_break_comment' => ['comment_text' => 'fallthrough'],
        'no_empty_comment' => true,
        'no_empty_statement' => true,
        'no_extra_blank_lines' => true,
        'no_leading_import_slash' => true,
        'no_leading_namespace_whitespace' => true,
        'no_singleline_whitespace_before_semicolons' => true,
        'no_spaces_around_offset' => true,
        'no_trailing_comma_in_singleline' => true,
        'no_whitespace_before_comma_in_array' => true,
        'no_whitespace_in_blank_line' => true,
        'no_unused_imports' => true,
        'normalize_index_brace' => true,
        'object_operator_without_whitespace' => true,
        'phpdoc_align' => ['align' => 'left'],
        'phpdoc_scalar' => true,
        'return_type_declaration' => ['space_before' => 'none'],
        'short_scalar_cast' => true,
        'single_trait_insert_per_statement' => true,
        'space_after_semicolon' => true,
        'standardize_not_equals' => true,
        'trailing_comma_in_multiline' => ['elements' => ['arrays']],
        'trim_array_spaces' => true,
        'visibility_required' => ['elements' => ['property', 'method']],
        'whitespace_after_comma_in_array' => true,
        'return_assignment' => true,
        'single_import_per_statement' => true,
        'no_trailing_whitespace_in_string' => true,
    ])
    ->setFinder($finder);

```

### Code snippet that reproduces the problem

  ```php
    /**
      * Returns singleton instance of the importer
      *
      * @static
      * @param DatabaseConnection $db
      * @return Importer
      */
    public static function get_instance(DatabaseConnection $db, $vendor_id): Importer
 ```

with just `phpdoc_align`, but not `phpdoc_indent` active, this will be converted into

```diff
--- /Users/pilif/Sites/xxx/lib/ImportHelpers/importer.php
+++ /Users/pilif/Sites/xxx/lib/ImportHelpers/importer.php
@@ -20,8 +20,8 @@
       * Returns singleton instance of the importer
       *
       * @static
-      * @param DatabaseConnection $db
-      * @return CustomerImporter
+       * @param DatabaseConnection $db
+       * @return CustomerImporter
       */
```

### LINKED ISSUE #7317: `ReturnToYieldFromFixer` error on file return
### Description

When run in files simply returning arrays, such as configuration files, shouldBeFixed method errors in the process of detecting the end of the array: https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/blob/master/src/Fixer/ArrayNotation/ReturnToYieldFromFixer.php#L85

The next thing in the file is the end of it but the fixer assumes there should be something else (assumes the return is inside a method/function) when actually in this case the tokens index is null and the expression fails with "Illegal offset type"

### Runtime version

PHP CS Fixer 3.28.0 Jump & Run by Fabien Potencier and Dariusz Ruminski.
PHP runtime: 8.2.10

### Code snippet that reproduces the problem

```php
<?php

use Slim\Factory\ServerRequestCreatorFactory;
use Slim\Interfaces\ServerRequestCreatorInterface;

return [
    ServerRequestCreatorInterface::class
        => static fn(): ServerRequestCreatorInterface => ServerRequestCreatorFactory::create(),
];
```

### PR DESCRIPTION
**Pull request by juliangut**
Hopefully fixes #7317

### CODE REVIEW

**Comment by Wirone** [comment]
Thanks @juliangut for the contribution, but according to the [contributing guide](https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/blob/master/CONTRIBUTING.md#development) you shoul provide first commit with test case that reproduces the issue, and after CI failure provide the fix 🙂. Minimal requirement is a test case along with a fix, without test case we can't merge it.

**Comment by juliangut** [comment]
@Wirone hope the PR now follows contribution guidelines

**Comment by SpacePossum** [comment]
could you add this test?:  (it will pass btw)

```php
        yield [
            '<?php
function foo(): iterable { return $z; }

return [1,2] ?>  X  <?php { echo 2; }'
        ];
```

I think your PR/fix is solid :+1:

**Comment by Wirone** [comment]
> [use yoda style you must](https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/pull/7318/commits/2a3d126e8fdf114863936c38d28e3d1cf90537bc)

❤️😆

Looks good, please add @SpacePossum's test case, rebase the branch and it'll be ready for merge 👍.

**Review by Wirone — APPROVED** [review]

**Comment by Wirone** [comment]
Thanks @juliangut and welcome to Fixer's contributors group 🍻!

**Comment by SpacePossum** [comment]
thanks @juliangut , nice fix :)

**Pull request merged**
