### PR TITLE
DX: exclude Dockerfile from dist

### PR DESCRIPTION
**Pull request by kubawerlos**

### CODE REVIEW

**Review by Wirone — CHANGES_REQUESTED** [review]
I believe there are more files that should be excluded from dist file, so if we want to do this, let's do it once for all 🙂.

image

**Comment by kubawerlos** [comment]
@Wirone I do not see any others, which files would that be?

**Comment by Wirone** [comment]
IMHO:

- `ci-integration.sh`
- `logo.md`
- `logo.png`
- `UPGRADE-v3.md`: users who install v3 most probably already did the migration, and if not, they have v2 installed and this file is not present there. IMHO anyone who needs to migrate will look at it online. But I won't insist on this one.
- `feature-or-bug.rst` also is not needed in the dist file, if anyone want to report an issue, will do it online and can read it.

**Comment by kubawerlos** [comment]
* `ci-integration.sh` - it was needed in `HelpCommand` once, not needed any more there, but in theory, someone might be using it in CI, I will not claim it is not needed
* `logo.md` - I guess it is legal stuff for `logo.png`
* `logo.png` - anyone opening `README.md` on `vendor` will then have a missing image at the very top
* `UPGRADE-v3.md`: same can be said about `README.md`, hard to be objective about it for me, @keradus, any thoughts?
`feature-or-bug.rst` - @keradus was your intention to add it to dist (https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/pull/6652)?

**Comment by Wirone** [comment]
- `ci-integration.sh` IMHO is not a public contract, nobody should rely on it. It is used in `tests/Smoke/CiIntegrationTest.php` and I believe this is internal file, that should be omitted in dist.
- `logo.md` I would completely remove this file from repo and would add info about the logo in the `README.md`. I don't get the point of this file 😅.
- `logo.png` I believe no-one needs logo displayed in the vendor dir file, I believe really small percent of people actually open `README.md` from `vendor`, and even if they do, lack of image is not a problem IMHO. But file is really small (18k) so whatever 🤷‍♂️ .
- `UPGRADE-v3.md` is not the same as readme, it's specific file that is rather needed _before_ installation. But since `README.md` contains references to `./doc/*` and those links does not work in dist file's readme, I would exclude both from dist (and then logo is not needed).

**Comment by Wirone** [comment]
To not block this particular valid change, let's discuss other files later and just merge this.

**Review by Wirone — APPROVED** [review]

**Comment by Wirone** [comment]
Thanks @kubawerlos 🍻

**Pull request merged**
