### PR TITLE
depr: `nullable_type_declaration_for_default_null_value` - deprecate option that is against `@PHP84Migration`

### PR DESCRIPTION
**Pull request by keradus**
ref #7774

### CODE REVIEW

**Review by julienfalque — APPROVED** [review]

**Comment by Wirone** [comment]
FYI: I've changed `chore` to `feat`, because SemVer [specifies it explicitly](https://semver.org/#spec-item-7) that deprecations in public API have to change minor version, so basically it's a feature ("net negative", but still).

**Comment by keradus** [comment]
OK that deprecation is bumping `minor` in SemVer.
wondering if `feat` category fits best, maybe we shall have dedicated `depr` category. we will deprecate more things soon and see them in features section of release changelog may be coubter-intuitive

**Comment by Wirone** [comment]
IMHO if there's "deprecate" in the title then it's enough. For automated release notes maybe `depr:` or `feat(depr):` will be required, but we're not there yet.

**Comment by keradus** [comment]
let me go with depr variant then.

**Pull request merged**
