### PR TITLE
minor: Deprecate BracesFixer

### PR DESCRIPTION
**Pull request by julienfalque**
## TODO

- [x] Deprecate `SingleSpaceAfterConstructFixer` in favor of a new `SingleSpaceAroundConstructFixer` that would also fix space *before* the `use` keyword for anonymous functions.
  - moved to #6857
- [x] Drop custom code in `applyxFix()` and rely on `SingleSpaceAroundConstructFixer` instead

### CODE REVIEW

**Comment by julienfalque** [comment]
Current Travis failure seems to be a bug in PHP. I have submitted a bug report on [PHP tracker](https://bugs.php.net/bug.php?id=79393).

**Comment by salarmehr** [comment]
Any update about this PR?

**Comment by kubawerlos** [comment]
@salarmehr Julien extracted 1st fixer to https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/5751 - do not hesitate and make a proper review there.

**Comment by SpacePossum** [comment]
just a note, as this is a `draft` and a very big PR, I assume no review is expected on it?

**Comment by keradus** [comment]
@julienfalque , please go ahead with this one! :) all else got merged!

**Comment by jrmajor** [comment]
> Deprecate `SingleSpaceAfterConstructFixer` in favor of a new `SingleSpaceAroundConstructFixer` that would also fix space before the use keyword for anonymous functions.

If `SingleSpaceAroundConstructFixer` also handled spacing around the `fn` and `=>` in arrow functions, it would be useful for #6547.

**Comment by keradus** [comment]
@julienfalque , do you think we can finalise this PR?
I would love to see it merged!

**Comment by julienfalque** [comment]
It's still WIP on my laptop, have to find some time to 🙂

**Comment by keradus** [comment]
eager to see that happening ! take your time ;)

**Comment by keradus** [comment]
@julienfalque , any chances for you to pick it up?
would be great to get rid of Braces fixer!

**Comment by keradus** [comment]
I let myself to pick it up.

- TODO 1: https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/pull/6857
- TODO 2: last commit

**Review by Wirone — APPROVED** [review]

**Comment by keradus** [comment]
I know that this PR looks small and simple, but only because most of work to make this happen got extracted to smaller, independent PRs [for easier review and faster merge].

Kudos for making all of that happen, @julienfalque ! that was one of the biggest effort we had in whole Fixer project!

**Comment by kubawerlos** [comment]
Go away, you evil fixer 🍾

**Comment by keradus** [comment]
I think that was one of the oldest fixer we ever had.

and one of first ones that I created. https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/pull/472

it took ages to have it in shape that was allowing to merge it. so many things learnt during that. time for retire indeed

**Comment by julienfalque** [comment]
Thank you @keradus for finishing this!

**Pull request merged**
