### PR TITLE
NoSuperfluousPhpdocTagsFixer - support for class constants

### PR DESCRIPTION
**Pull request by mos-ru**
Is supposed to close https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/issues/5991

### CODE REVIEW

**Comment by mos-ru** [comment]
I supposed to close #5991

**Comment by GrahamCampbell** [comment]
We should only do this for final or private constants, or for those in final classes. Parent classes can override, and the type information is needed to determine if the override is valid or not.

**Comment by GrahamCampbell** [comment]
Needs rebasing. :)

**Comment by Wirone** [comment]
I'm going to close this because:

- It's almost 2 years old and needs rebasing
- source branch was removed by the author of a PR
- I don't see much value in it, especially considering [typed class constants](https://wiki.php.net/rfc/typed_class_constants) upcoming in PHP 8.3

I'll mark it with `status/to recover` so it can be continued by some volunteer 😉.

PS. I moved one comment's content to PR's description, so I removed that comment as it wasn't needed anymore.

**Pull request closed without merging**
