### PR TITLE
chore: Use `list` over `array` in more places

### PR DESCRIPTION
**Pull request by keradus**

### CODE REVIEW

**Comment by kubawerlos** [comment]
Can we add a rule to `.php-cs-fixer.dist.php` to enforce this?

**Comment by Wirone** [comment]
Exactly: add the rule, apply, fix PHPStan issues if any occur, forget.

**Comment by keradus** [comment]
as I was describing somewhere in first of PRs in this style - that's the goal.

yet, we cannot blindly replace `foo[]` or `array<foo>` into `list<foo>`, as sometimes we need to use `list<key, foo>`. I also do not want to blindly apply `list<key-type, foo>`.


auto-apply here cannot to this, but when we are clean, it can prevent new cases.

**Comment by keradus** [comment]
example where blind application would apply wrong type, from very this PR:
https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/pull/7905/files#diff-f0f5829e3bd024ac8f67d5e42dc491600f7bde0a372793a1da755c1549369838R506

**Comment by keradus** [comment]
> PHPStan

as mentioned in previous PR, PHPStan is not detect the type issue between `list<foo>` vs `array<int, foo>` (assoc array, non-list)

**Review by Wirone — APPROVED** [review]

**Pull request merged**
