### PR TITLE
fix: `NoSpaceAroundDoubleColonFixer` must run before `MethodChainingIndentationFixer`

### LINKED ISSUE #7699: `method_chaining_indentation` should be executed after `no_space_around_double_colon`
## Bug report

Linked with [Pint Issue 234](https://github.com/laravel/pint/issues/234) posted by @shengslogar

### Description

Because of its alphabetical placement, the rule `method_chaining_indentation` takes precedence over `no_space_around_double_colon`, even though it should be executed after `no_space_around_double_colon`.

A problematic fix will occur if `method_chaining_indentation` is set before `no_space_around_double_colon` following alphabetical order.

### Runtime version

```
PHP CS Fixer 3.46.0 Three Keys by Fabien Potencier and Dariusz Ruminski.
PHP runtime: 8.2.14
```

### Used command

```
vendor/bin/php-cs-fixer fix -vvv test.php
```

### Configuration file

```php
use PhpCsFixer\Finder;
use PhpCsFixer\Config;


$finder = ( new Finder() )->in( __DIR__ );


return ( new Config() )
    ->setUsingCache( false )
    ->setRules( [
        'method_chaining_indentation' => true,
        'no_space_around_double_colon' => true
    ] )
    ->setFinder( $finder );
```

### Code snippet that reproduces the problem in `test.php`

`Before`

  ```php
$formattedIncorrectly = Foo::bar
    ::baz()
                    ->where('id', 1)
    ->firstOrFail();

$formattedCorrectly = Foo::bar
::baz()
    ->where('id', 1)
    ->firstOrFail();
  ```

`After`

```php 
$formattedIncorrectly = Foo::bar::baz()
        ->where('id', 1)
        ->firstOrFail();

$formattedCorrectly = Foo::bar::baz()
    ->where('id', 1)
    ->firstOrFail();
```

`Expected`

```php
$formattedIncorrectly = Foo::bar::baz()
    ->where('id', 1)
    ->firstOrFail();

$formattedCorrectly = Foo::bar::baz()
    ->where('id', 1)
    ->firstOrFail();
```

### PR DESCRIPTION
**Pull request by mho22**
Fixes #7699.

### CODE REVIEW

**Comment by mho22** [comment]
@Wirone Considering the minor changes that were added, the static code analysis check seems a bit peculiar.

**Comment by Wirone** [comment]
@mho22 hard to tell, does it work correctly when you execute `composer qa` locally?

**Comment by mho22** [comment]
@Wirone No, indeed.

I get this error

```
PHP-CS-Fixer [master] composer qa
> Composer\Config::disableProcessTimeout
> ./dev-tools/check_file_permissions.sh
"php-cs-fixer" is executable
No wrong permissions detected.
> ./dev-tools/check_trailing_spaces.sh
Trailing whitespaces detected:
tests/Fixer/Phpdoc/PhpdocAlignFixerTest.php:697:     * @param mixed    $bar    Description word_with_ą
tests/Fixer/Phpdoc/PhpdocAlignFixerTest.php:704:     * @SuppressWarnings(PHPMD.UnusedLocalVariable) word_with_ą
tests/Fixer/Phpdoc/PhpdocAlignFixerTest.php:714:     * @param mixed $bar Description word_with_ą
tests/Fixer/Phpdoc/PhpdocAlignFixerTest.php:721:     *   @SuppressWarnings(PHPMD.UnusedLocalVariable) word_with_ą
tests/Fixer/Phpdoc/PhpdocTrimFixerTest.php:54: * @return int количество деактивированных
tests/Fixer/Phpdoc/PhpdocTrimFixerTest.php:66: * Test à
tests/Fixer/Whitespace/NoTrailingWhitespaceFixerTest.php:95:garçon, si bien qu'il ne savait s'il fallait garder sa casquette à
Script ./dev-tools/check_trailing_spaces.sh handling the self-check event returned with error code 3
Script @self-check was called via quality-assurance
Script @quality-assurance was called via qa
```

I managed to bypass the error using `composer test:integration`.

**Comment by Wirone** [comment]
There are many Composer scripts that are building blocks for `qa`. Looking at the pipeline here, you should locally look at `composer auto-review` and `composer test`. In general, you should be able to pass the whole QA suite locally to be able to effectively work with Fixer.

**Comment by mho22** [comment]
@Wirone I think the CI could possibly be broken by some unrelated change - as indicated in another recent PR comment ? : https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/pull/7724#discussion_r1451596156

**Comment by mho22** [comment]
@Wirone I've finally passed all the checks. Thanks for following up.

**Review by Wirone — APPROVED** [review]
FYI: before this PR the result of using those 2 rules depended on the way how Fixer was executed - you could have 2 different outcomes depending on the order of the rules:

image

After this PR it does not matter in which order rules are added to the final ruleset, their priorities determine the actual order.

**Comment by Wirone** [comment]
Thank you @mho22 🍻!

**Pull request merged**
