### PR TITLE
DX: update Symfony rule set

### PR DESCRIPTION
**Pull request by kubawerlos**
[All these](https://github.com/symfony/symfony/blob/v6.2.10/.php-cs-fixer.dist.php#L31-L37) (obviously except `header_comment`) shouldn't need to be added separately, but be in `@Symfony` and `@Symfony:risky` sets already.

### CODE REVIEW

**Review by Wirone — APPROVED** [review]
Again: shouldn't dist config be changed? 😅

**Comment by kubawerlos** [comment]
> Again: shouldn't dist config be changed? sweat_smile

Reading the comment in the dist confing probably better would be to disable `modernize_strpos` for `@PhpCsFixer:risky` (until we stop supporting PHP < 8).

**Review by Wirone — APPROVED** [review]

**Comment by Wirone** [comment]
Thanks @kubawerlos 🍻

**Comment by kubawerlos** [comment]
@darkin1 the part:

> using implicit type rather than explicit seems to not be recommended

for me applies to pretty much everything, it was added not because it is good practice, but because it is in current Symofny's standards.

**Pull request merged**
