### PR TITLE
feature: Alphabetical array key sort fixer

### PR DESCRIPTION
**Pull request by MohannadNaj**
- This PR is a resubmission of ( PR #5492 ) which is related to ( Issue #4552 ). Responding to @Wirone 's latest comment in the PR 3 days ago.

- It contains a fixer that will sort array keys in alphabetical order. 

- Original commits authored by @auymaz and @LarsGrevelink .. I only did some additional rebase fixes (methods signatures, rewording the option description, ensuring the tests are passing). [Comparison view of added commits](https://github.com/mohannadnaj-forks/PHP-CS-Fixer/compare/477e95f36bd7a6ad104330ebc054562c850c6f6...alphabetical-array-key-sort-fixer)

- Note: The original PR was submitted to v2.18.2

```
$arr = [
    'c' => 'foo',
    'a' => 'foo',
    'b' => 'foo',
];

// After

$arr = [
    'a' => 'foo',
    'b' => 'foo',
    'c' => 'foo',
];
```

### CODE REVIEW

**Comment by LarsGrevelink** [comment]
Hi @MohannadNaj ! I didn't see the fixes when we were already working on it, sorry about that. We would prefer to keep all the code in #5492 to prevent multiple versions of the code to start living elsewhere in case changes are needed. If you could decline your PR we make sure the reviewers are not reviewing the incorrect version and keep the list of pull requests cleaner. Thanks again though, hopefully it will be merged soon. :)

**Comment by Wirone** [comment]
@MohannadNaj thank you very much for your work on tebasing this, but I agree with @LarsGrevelink and I would like to keep original PR too. My comment there was addressed to original authors and yeah, without response in reasonable time we could think about rebasing it on our own (like I did for several other PRs that seemed interesting), but since PR was picked up let's continue there 🙂. Sorry, but please don't give up, you can help us in many ways!

**Comment by MohannadNaj** [comment]
@LarsGrevelink @Wirone Sure! .. and Thank you so much I'm actually glad to see it continued in the same PR 🤍🙏  

Personally, My #1 use case for this fixer would be: localization files... sorting the lines alphabetically reduces git conflicts + allows for an easy/quick eye scan of what's out of sync when comparing the same file across multiple languages.

**Comment by LarsGrevelink** [comment]
@MohannadNaj everything is passing now on the on the main PR so if the code Gods are with us it might not take too much effort to get merged into master. In case you already want to use it before it's getting released, you can add it as a custom fixer as we did with our own project. A description about this can be found [here](https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/blob/master/doc/custom_rules.rst).

**Pull request closed without merging**
