### PR TITLE
Revert "bug: Fix phpDoc align when there is inconsistent spacing after comment star"

### PR DESCRIPTION
**Pull request by GrahamCampbell**
Reverts PHP-CS-Fixer/PHP-CS-Fixer#7012

### CODE REVIEW

**Comment by mvorisek** [comment]
Partial revert to fix https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/issues/7048 might be needed as the fix is done more "by hope" than regular grammar.

Please update this PR to a minimal revert with a test case. I belive we can still keep at least 0 - 2 spaces (1 regular + 1) fixed.

**Comment by GrahamCampbell** [comment]
If I get time, I will send a new PR, where we can retain this test case, but I feel it is less broken with this PR reverted, due to the high number of repos that use the formatting in the posted issue (and they use php-cs-fixer, directly or indirectly).

**Comment by Wirone** [comment]
Such revert only makes sense if @keradus has time for making a release. If not, there's time for some better solution.

**Comment by mvorisek** [comment]
@GrahamCampbell see #7050 PR with proper fix

**Comment by Wirone** [comment]
Closing this because of [this](https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/pull/7050#issuecomment-1596961865).

**Pull request closed without merging**
