### PR TITLE
feat: Support for attributes in `method_argument_space`

### LINKED ISSUE #6546: Support for attributes in `method_argument_space`
What I'd like to achieve:

```diff
class MyClass
{
    public function __construct(
        string $id,
-       #[ORM\Column(type: Types::STRING, nullable: true)] #[Groups(['get_my_class'])] private ?string $name = null,
+
+       #[ORM\Column(type: Types::STRING, nullable: true)]
+       #[Groups(['get_my_class'])]
+       private ?string $name = null,
    ) {}
```

Is it possible with current rules?

### PR DESCRIPTION
**Pull request by Wirone**
Fixes #6546.

Example snippet from the issue fixed with changes provided in this PR:
image

### CODE REVIEW

**Review by kubawerlos — APPROVED** [review]

**Comment by JarJak** [comment]
Wow, thanks for quick fix @Wirone ! <3

**Comment by ruudk** [comment]
Thanks @Wirone 🤩 👏

**Comment by ruudk** [comment]
Now all we need is a tagged release ☺️

**Comment by nexik** [comment]
How to revert config to previous behaviour? It is BC Break. 
```
     public function collection(
         Request $request,
-        #[ValueResolver('date_range')] DateRange $dateRange,
-        #[ValueResolver('pagination')] OffsetPagination $pagination,
+        #[ValueResolver('date_range')]
+        DateRange $dateRange,
+        #[ValueResolver('pagination')]
+        OffsetPagination $pagination,
         AggregatedEventsQuery $query
     ): Response {
    ----------- end diff -----------


Applied checkers:

 * PhpCsFixer\Fixer\FunctionNotation\MethodArgumentSpaceFixer
```

**Comment by Wirone** [comment]
> It is BC Break.

[No, it's not](https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/issues/7260#issuecomment-1698808046).

**Comment by nexik** [comment]
Thanks for the link. It helps me to understand the background and decision process. You have the full right to define what BC Break for your project means (For it is much more than the current unit test in the codebase). My take from the situation is that I cannot trust semver for this project when upgrading dependencies for my projects.

**Comment by Wirone** [comment]
> My take from the situation is that I cannot trust semver for this project when upgrading dependencies for my projects.

I believe it's an overstatement. The only public contract we can agree on are our test cases, and all of them must pass when we add, modify or refactor something. If something is not covered with tests, then there's no contract between us and our users, hence we can't talk about BC break. If you use built-in rulesets in your config instead of creating your own ruleset from scratch, then you can't complain that some behaviour has changed, because you explicitly opted-in for someone others' rules, which may be changed at any point. And even if you had fully custom config and some specific rule started to behave differently, then again: if some case was not covered before, we must introduce default behaviour and it's possible that it will affect users' codebase, but only because it wasn't covered before. With your approach even bugfix can be a BC break, because implementation could be wrong or some edge case was not covered, and rule acts differently before and after the fix. Sorry to hear that newly introduced feature does not fit your needs, but I believe change provided in this PR is what should be the default behaviour of `ensure_fully_multiline` strategy. If you need different output, please open [feature idea discussion](https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/discussions/new?category=feature-ideas) so we can figure out the solution.

**Comment by VincentLanglet** [comment]
> > It is BC Break.
> 
> [No, it's not](https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/issues/7260#issuecomment-1698808046).

Hi @Wirone,  I have trouble to agree with this statement.
Looking at your messages, I'm pretty sure you won't change opinion, but I'd like to share mine.

> Hi @guelosuperstart, thanks for the report. I understand your consternation after the upgrade, but this is not a bug 🙂. First of all, before v3.24 attributes were not covered by Fixer in any way, there were not test cases for that. Behavior introduced in v3.24 is a new default, which is compliant with [PER-CSv2 §12.2](https://www.php-fig.org/per/coding-style/#122-placement):
> 
> > Attributes on classes, methods, functions, constants and properties MUST be placed on their own line, immediately prior to the structure being described.
> > For attributes on parameters, if the parameter list is presented on a single line, the attribute MUST be placed inline with the parameter it describes, separated by a single space. If the parameter list is split into multiple lines for any reason, the attribute MUST be placed on its own line prior to the parameter, indented the same as the parameter. If the parameter list is split into multiple lines, a blank line MAY be included between one parameter and the attributes of the following parameter in order to aid readability.

Following the PER-CS to "update/change"  fixer should still be considering as a BC break in some case.

Here the description of the rule is (or was)
> In method arguments and method call, there MUST NOT be a space before each comma and there MUST be one space after each comma. Argument lists MAY be split across multiple lines, where each subsequent line is indented once. When doing so, the first item in the list MUST be on the next line, and there MUST be only one argument per line.

Given this description, the example
```
public function collection(
         Request $request,
         #[ValueResolver('date_range')] DateRange $dateRange,
         #[ValueResolver('pagination')] OffsetPagination $pagination,
         AggregatedEventsQuery $query
     )
```
was respecting the rule "there MUST be only one argument per line".
Indeed, attributes are not arguments.

PER-Cs are introducing new CS-rules because PHP syntax is evolving ; it's good that PHP-Cs-Fixer are able to propose Fixer for PER-Cs but it would be better to not do this against the PSR12.

In my mind the "0 BC-break way" would have been to
- introduce an option "on attribute => 'ignore/ensure_fully_multiline/ensure_single_line'"
- use 'ignore' by default
- use 'ensure_fully_multiline' in PER-Csv2

That's being said ; thanks for all your work.

**Comment by Wirone** [comment]
Hi @VincentLanglet, thanks for the input. I agree that in ideal world it would be better to introduce option for it, but in real world with limited resources we just can't support every scenario 🙂. The truth is that we have unfinished PSR-12, PER-CS v1 and PER-CS v2, and adding each of the missing rules to each and any of these may cause changes in the users' codebase and may be considered as BC break. But is it BC break actually? People opting-in for (living) coding standard should be aware that it may change (especially that issue related to unfinished rulesets are pinned to the project). This rule can be used without inheriting it from the ruleset, though 🤔. I have mixed feelings here, because as I said before attributes were not covered by the contract before (tests), so this was the new default that is not a BC break for me. I believe we could introduce the option and use it accordingly in each ruleset, but keeping current behavior as default to at least keep BC on the rule level (because there would be break on some rulesets' level). What do you think?

**Comment by VincentLanglet** [comment]
>  agree that in ideal world it would be better to introduce option for it, but in real world with limited resources we just can't support every scenario 🙂. 

Sure, I understand this. I always hard to not end with tons of config options to maintain.

> The truth is that we have unfinished PSR-12, PER-CS v1 and PER-CS v2, and adding each of the missing rules to each and any of these may cause changes in the users' codebase and may be considered as BC break. But is it BC break actually? People opting-in for (living) coding standard should be aware that it may change (especially that issue related to unfinished rulesets are pinned to the project). 

I think it depends on the point on view.
When changing the behavior of a rule I would say it's either a Bugfix or a BC-break.
In my mind, feature are either new rules or new options.

Here, the non-support for attributes was never reported as a bug, so it's not really a bugfix.
(And you've opened the PR as a feature, so you don't think it's a bugfix too)
Therefor with "my" logic, it's a BC break.

But sure the opiniopn is debatable and coding standard can change, that's understandable.
The only issue is that currently people cannot achieve the previous behavior without downgrading and fixing the version.

> This rule can be used without inheriting it from the ruleset, though 🤔. I have mixed feelings here, because as I said before attributes were not covered by the contract before (tests), so this was the new default that is not a BC break for me. I believe we could introduce the option and use it accordingly in each ruleset, but keeping current behavior as default to at least keep BC on the rule level (because there would be break on some rulesets' level). What do you think?

Seems like the best solution to me.

**Comment by VincentLanglet** [comment]
@Wirone The option could something like https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/compare/master...VincentLanglet:PHP-CS-Fixer:attributes?expand=1

Any recommendation about the naming ?

**Comment by Wirone** [comment]
> I think it depends on the point on view. When changing the behavior of a rule I would say it's either a Bugfix or a BC-break. In my mind, feature are either new rules or new options.
> 
> Here, the non-support for attributes was never reported as a bug, so it's not really a bugfix. (And you've opened the PR as a feature, so you don't think it's a bugfix too). Therefore with "my" logic, it's a BC break.

Yes, it was a feature, implementation of previously non-existing case. Whether it's a BC break or not is a matter of perspective, as you already pointed out. However, I was referring to changes like #7302 which introduces change to existing ruleset and may affect codebases of people that are using this ruleset. But it's not a BC-break since the default behaviour of fixer itself wasn't changed, only the ruleset was changed and it's OK because if you use ruleset you accept upstream's coding standard. In case of `method_argument_space` it was slightly different, I agree, but still it did not violate _our_ contract, because we did not have tests ensuring attributes won't get reformatted 😉. Anyway, I believe introducing configuration option for that is a good step.

> The option could something like (...). Any recommendation about the naming ?

I think your proposal is OK, as an alternative it could be `attribute_placement` with options: `ignore`,  `same_line` and `standalone` (and maybe `standalone_if_multiple`?). PS. option's description needs to be updated, because it's copied from `on_multiline` 🙂.

**Comment by VincentLanglet** [comment]
> I think your proposal is OK, as an alternative it could be `attribute_placement` with options: `ignore`, `same_line` and `standalone` (and maybe `standalone_if_multiple`?). PS. option's description needs to be updated, because it's copied from `on_multiline` 🙂.

I like this, I updated then https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/pull/7320

**Comment by guelosuperstart** [comment]
Hello  @Wirone, @VincentLanglet,

Great work 💪 

This hasn't been released yet, has it?

Thank you !

**Comment by Wirone** [comment]
@guelosuperstart it was, few minutes ago, in 3.31 🙂.

**Comment by guelosuperstart** [comment]
Hello @Wirone, @VincentLanglet,

Great !! it work well

Thank you very much 👌

**Pull request merged**
