### PR TITLE
fix: work correctly for a switch/case with ternary operator

### PR DESCRIPTION
**Pull request by kubawerlos**
Fixes https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/issues/7740

### CODE REVIEW

**Review by Wirone — COMMENTED** [review]
Shouldn't be there more integration tests and priority graph entries since priorities of 3 fixers were changed?

**Comment by kubawerlos** [comment]
> Shouldn't be there more integration tests and priority graph entries since priorities of 3 fixers were changed?

That's not the case. To be able to add `tests/Fixtures/Integration/misc/ternary_operator_spaces,operator_linebreak.test` (notice that it is `misc` category, not `priority`) the 2 fixers there need (there is a test for this) to have different priorities.

Then, `operator_linebreak` is not in the priorities graph, thus, it has priority `0` and I could not invent any priority case for it. Not being in the priorities graph means priority has to stay `0` (there is a test to check that if the priority is different than `0` then there must be some priority test for such fixer).

So, as changing the priority of `operator_linebreak` was a no-go, I've changed the priority of `ternary_operator_spaces`, and the others are the result of that change.

**Comment by Wirone** [comment]
@kubawerlos unfortunately I can't rebase and merge, so please update the PR when you have time 🙂.

**Comment by Wirone** [comment]
Thank you @kubawerlos 🍻

**Pull request merged**
