### PR TITLE
fix: StatementIndentationFixer - do not crash on ternary operator in class property

### PR DESCRIPTION
**Pull request by kubawerlos**
Fixes https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/issues/7896

### CODE REVIEW

**Comment by Wirone** [comment]
That ParaUnit output is so meeeeehhhh 😩

**Comment by keradus** [comment]
mind to elaborate on your comment, @Wirone ?

**Comment by kubawerlos** [comment]
I guess he means the failing job, it is extremely hard to see anything in the ParaUnit output.

**Comment by Wirone** [comment]
Exactly what @kubawerlos said. Finding something meaningful on mobile in ParaUnit failed job output is kind of mission impossible 😩.

**Comment by kubawerlos** [comment]
https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/pull/7900 fixes the CI that fails here.

**Review by Wirone — APPROVED** [review]

**Comment by kenjis** [comment]
Thank you for the quick fix!

**Pull request merged**
