### PR TITLE
feature: Make `UnaryOperatorSpaces` configurable

### LINKED ISSUE #4674: Deprecate not_operator_with_space and not_operator_with_successor_space
I noticed rules `not_operator_with_space` and `not_operator_with_successor_space` are quite similar so they could be merged into a single configurable rule. Then I remembered we also have `unary_operator_spaces`.

IMO we could:
* add an `operators` option to `unary_operator_spaces` (similar to the option for `binary_operator_spaces`)
* deprecate `not_operator_with_space` and `not_operator_with_successor_space` as their scope would be covered by the new option of `unary_operator_spaces`

WDYT?

### PR DESCRIPTION
**Pull request by paulbalandan**
Closes #4674 

This uses the suggestions included in the feature request.

Not sure if the description is warranted here. To me, it can clear potential misunderstandings as to how the options work. Happy to remove if explaining the obvious. 😊

### CODE REVIEW

**Comment by SpacePossum** [comment]
>Not sure if the description is warranted here.

never hurts ;) but I get it, I rarely get around writing one either :P

First off, thanks for all the effort and taking the time to go through the issue reported and building a solution!
I really like the idea of unifying the  `not_operator_with_space` and `not_operator_with_successor_space` under `unary_operator_spaces`. It makes sense to me to have one rule with options. It removes conflicting rules and puts all logic (complexity) into one rule :+1: 

However the PR goes a bit beyond that and I'm not sure if I agree with all of it. The proposed solution adds options for spacing beyond the things that are proposed to put into the one rule. 
While having options to say `I like one-space or no space around "!"` are great, it also allows for fixing `$a++;` into `$a ++;` (IIUC the PR).  This to me is not in scope of the tool. We should encourage people to use common code styles and I don't see this (as example) as part of that. 

I understand that after all the work you did for one operator (`!`) allowing it for all operators seems like a great win. However, when we do allow this we, as community, agree to up hold this feature under BC promise. This I would like to suggest not do, as it is out of scope and comes with a maintenance cost for a feature that was not part of the original ask (in 4674) nor asked in some other issue. I would like to suggest to scope down this PR a bit for those reasons.

Again great work, no doubt! Would like to hear opinions on it, than again I'm just giving my opinion and that is all that is to it :)

**Comment by paulbalandan** [comment]
> However the PR goes a bit beyond that and I'm not sure if I agree with all of it. [...]

Hi @SpacePossum thanks for the comment. I understand your concern and do agree that some of the options would not lead to best practices code styles. Scoping down would be amenable to me. I'll just wait for more initial comments before continuing the work. Thanks again!

**Comment by Wirone** [comment]
@paulbalandan I've rebased your branch because there were several changes added to the `master` branch and I wanted to include those changes here. Failures are the same as before (2 "Code build on input code must match expected code", 2 "Fixer must be a candidate for input code"), I've fixed for you one auto-review test related to the rebase.

> it also allows for fixing `$a++;` into `$a ++;` (IIUC the PR). This to me is not in scope of the tool.

@SpacePossum I don't see it being "out of the scope", because Fixer already supports many scenarios that I personally see as "non-standard" or unneeded (e.g. all the align fixes that I personally dislike). If the logic for handling spaces around operator is unified in one place, then it should be easy to maintain (IMHO easier than when it's spread across several fixers). In other words: it's OK to continue with this change 👍.

**Comment by paulbalandan** [comment]
2nd commit fixes the failing test in `NotOperatorWithSpaceFixer`.

The 2nd commit implies that `UnaryOperatorSpacesFixer` is not a true proxy for `NotOperatorWithSpaceFixer.` The latter fixer does not fix if there are already existing whitespaces around `!`. It only fixes if there is no whitespace. However, the former fixer ensures there is a single whitespace around `!`. Thus, there are two options:

1. Do not proxy NotOperatorWithSpaceFixer against UnaryOperatorSpacesFixer. Just deprecate it. Suggest no replacement.
2. Treat the unfixing as a bug and proceed with the 2nd commit.

**Comment by Wirone** [comment]
@paulbalandan when someone else rebases your branch, the first thing you need to do before continuing work is reset to remote version with `git fetch && git reset --hard @{u}` ([info](https://stackoverflow.com/a/61490618/842480)). If you had more commits than were published (and rebased), then you need to do `rebase --onto` and move only non-published commits to the top of the rebased branch. [Here's my thread about rebase](https://twitter.com/_Codito_/status/1601188935199510529), there's also info about `--onto` and how to do it in PHPStorm 😉.

**Comment by SpacePossum** [comment]
>I don't see it being "out of the scope", because Fixer already supports many scenarios that I personally see as "non-standard" 

How is that a reason to continue? I'm fine with us not agreeing, but I struggle to follow a lot of the time. Lets say I want a rule that fixes `$a = $a + 1;` into `++$a`, than you go "no, lets make the rule go both ways", stopping process. Than if I would make the rule go both ways,than in PR's like this you go  "I see thing already "non-standard", no surprise : D

So, anyhow, I don't understand why you want to maintain logic that changes `$a++` into $a ++` , like I would never ever, I really can't see any justification where that is a good change.

**Comment by Wirone** [comment]
> Lets say I want a rule that fixes $a = $a + 1; into ++$a, than you go "no, lets make the rule go both ways", stopping process. Than if I would make the rule go both ways,than in PR's like this you go "I see thing already "non-standard", no surprise :D

Are you referring to real case from the past? Because I don't remember situation when I "blocked" anything just because of being 1-way.

> So, anyhow, I don't understand why you want to maintain logic that changes `$a++` into `$a ++` , like I would never ever, I really can't see any justification where that is a good change.

I would never ever used any horizontal align modes in fixers, yet we have such options. I would never ever include spaces inside parentheses, yet it's a WordPress standard and there's PR #5709 for that, that I personally continue to work on to not waste contributor's work. It's not an argument for me 🙂. Anyway, I just shared _my_ opinion on that, which is not a final decision, because I am not a lead here. I just try to push things forward 🤷‍♂️.

@kubawerlos what do you think?

**Comment by kubawerlos** [comment]
> @kubawerlos I believe 2 points in Julien's issue weren't disjunctive, so why "2nd option"? IMHO those are steps, both to do.

I was not focused enough, in 2nd point I read "option" as "fixer", like merging 2 opposite fixers into 1 configurable.

**Comment by Wirone** [comment]
@paulbalandan sorry to see your work was not finished. Are you interested in continuing this?

**Comment by julienfalque** [comment]
I wanted to start working on #4674 and saw this PR. It's very similar to what I was about to implement. @paulbalandan do you want to reopen this PR?

I agree with @SpacePossum regarding the spacing with `++` or `--` which is not a good practice and should not be promoted somehow, but on the other hand the options proposed here gives more flexibility to users without requiring a lot of changes so IMO it's OK to have them with sane defaults.

**Comment by Wirone** [comment]
@julienfalque I believe it's totally OK to checkout @paulbalandan's PR and continue work under a new one, keeping authorship of original commits. I did it several times with stale or closed PRs 🙂.

**Comment by julienfalque** [comment]
Sadly branch was deleted, not sure I can do that

**Comment by Wirone** [comment]
@julienfalque you can [download the patch](https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/pull/7059.patch) and apply it locally with proper `--author` 🙂.

**Comment by julienfalque** [comment]
Good idea, but too many conflicts and I don't know the base commit. I'm going to work on an alternative PR in the meantime.

**Comment by keradus** [comment]
Remember we already hace some configuration in place.
if we think to deprecate one fixer and have it;'s logic in another fixer - it one story.

if we think to introduce possibility of new style configuration - it's other story, let's validate if there is a community behind given style before implementing 🙏🏻

**Comment by julienfalque** [comment]
@keradus I searched for examples and found the [rules for the `...` operator in Wordpress CS](https://developer.wordpress.org/coding-standards/wordpress-coding-standards/php/#spread-operator):
> When using the spread operator, there should be one space or a new line with the appropriate indentation before the spread operator

As I understand, the Wordpress community would benefit from the ability to enforce a single space before this operator and thus more flexible options.

There's also a second rule:
> When combining the spread operator with the reference operator (`&`), there should be no spaces between them

IMO this should be always done no matter the other options.

**Comment by Wirone** [comment]
>> When combining the spread operator with the reference operator (&), there should be no spaces between them
>
> IMO this should be always done no matter the other options.

This [does not make sense](https://3v4l.org/LjMhL) 🤔. You can't reference something that was exploded to pieces.

**Comment by julienfalque** [comment]
It's [valid](https://3v4l.org/GfIER) for variable-length argument lists.

**Pull request closed without merging**
