### PR TITLE
feat: allow PHPUnit 11

### PR DESCRIPTION
**Pull request by Chris53897**
Blocked by

- [x] https://github.com/PHP-CS-Fixer/phpunit-constraint-xmlmatchesxsd/pull/22
- [x] https://github.com/PHP-CS-Fixer/phpunit-constraint-isidenticalstring/pull/18

### CODE REVIEW

**Review by derrabus — APPROVED** [review]

**Review by kubawerlos — CHANGES_REQUESTED** [review]
PHPUnit 11 is not installed in any job right now, so there is no confirmation it actually works.

**Comment by Chris53897** [comment]
Thanks for pointing this out. I will Change the description.
In that case, please have a look at the blocking PRs.

**Comment by kubawerlos** [comment]
> please have a look at the blocking PRs.

both have failing CI, which has to be addressed first.

**Comment by keradus** [comment]
actually they are failing because Fixer version is not locked (I'm OK with that for those repos) and is not related to proposed change on it's own - I will solve that independently.

still, for this PR, we shall have a job which actually uses PHPUnit 11 to prove it works, as Kuba mentioned.

**Comment by Chris53897** [comment]
There is more blocking.
https://github.com/facile-it/paraunit/blob/2.x/composer.json#L30

**Comment by Wirone** [comment]
@Chris53897 you can just use `composer why-not phpunit/phpunit ^11` 🙂. I was going to check it when I have time, but you can do it yourself too.

**Comment by Chris53897** [comment]
I already did ;)

` composer why-not "phpunit/phpunit" 11.0.1

phpunit/phpunit           11.0.1     requires         phpunit/php-code-coverage (^11.0)                    
friendsofphp/php-cs-fixer dev-master does not require phpunit/php-code-coverage (but 10.1.11 is installed) 
phpunit/phpunit           11.0.1     requires         phpunit/php-file-iterator (^5.0)                     
friendsofphp/php-cs-fixer dev-master does not require phpunit/php-file-iterator (but 4.1.0 is installed)   
phpunit/phpunit           11.0.1     requires         phpunit/php-invoker (^5.0)                           
friendsofphp/php-cs-fixer dev-master does not require phpunit/php-invoker (but 4.0.0 is installed)         
phpunit/phpunit           11.0.1     requires         phpunit/php-text-template (^4.0)                     
friendsofphp/php-cs-fixer dev-master does not require phpunit/php-text-template (but 3.0.1 is installed)   
phpunit/phpunit           11.0.1     requires         phpunit/php-timer (^7.0)                             
friendsofphp/php-cs-fixer dev-master does not require phpunit/php-timer (but 6.0.0 is installed)           
phpunit/phpunit           11.0.1     requires         sebastian/cli-parser (^3.0)                          
friendsofphp/php-cs-fixer dev-master does not require sebastian/cli-parser (but 2.0.0 is installed)        
phpunit/phpunit           11.0.1     requires         sebastian/code-unit (^3.0)                           
friendsofphp/php-cs-fixer dev-master does not require sebastian/code-unit (but 2.0.0 is installed)         
phpunit/phpunit           11.0.1     requires         sebastian/comparator (^6.0)                          
friendsofphp/php-cs-fixer dev-master does not require sebastian/comparator (but 5.0.1 is installed)        
phpunit/phpunit           11.0.1     requires         sebastian/diff (^6.0)                                
friendsofphp/php-cs-fixer dev-master does not require sebastian/diff (but 5.1.0 is installed)              
phpunit/phpunit           11.0.1     requires         sebastian/environment (^7.0)                         
friendsofphp/php-cs-fixer dev-master does not require sebastian/environment (but 6.0.1 is installed)       
phpunit/phpunit           11.0.1     requires         sebastian/exporter (^6.0)                            
friendsofphp/php-cs-fixer dev-master does not require sebastian/exporter (but 5.1.1 is installed)          
phpunit/phpunit           11.0.1     requires         sebastian/global-state (^7.0)                        
friendsofphp/php-cs-fixer dev-master does not require sebastian/global-state (but 6.0.1 is installed)      
phpunit/phpunit           11.0.1     requires         sebastian/object-enumerator (^6.0)                   
friendsofphp/php-cs-fixer dev-master does not require sebastian/object-enumerator (but 5.0.0 is installed) 
phpunit/phpunit           11.0.1     requires         sebastian/type (^5.0)                                
friendsofphp/php-cs-fixer dev-master does not require sebastian/type (but 4.0.0 is installed)              
phpunit/phpunit           11.0.1     requires         sebastian/version (^5.0)                             
friendsofphp/php-cs-fixer dev-master does not require sebastian/version (but 4.0.1 is installed)           
`

**Comment by Jean85** [comment]
I'm working on https://github.com/facile-it/paraunit/pull/230 to allow PHPUnit 11 fully, the first release wasn't complete.
It should work now, but I'm having some issues in my CI, and this PR was one of the blockers :smile: I did a workaround to avoid the circular dependency, now I just have to fix a small issue in a test.

**Comment by Wirone** [comment]
Thank you @Jean85 🍻!

**Comment by Jean85** [comment]
Code coverage is failing since PHPUnit 11 requires a different format for the configuration: `coverage` nodes have to be renamed as `source`. This change is backward compatible ad available since PHPUnit 10.1, so you may have issues with PHPUnit 10.0 and lower, and in turn for PHP 8.0 and lower.

Splitting the config in two may be the only possible course of action.

**Comment by Wirone** [comment]
@Chris53897 thank you for taking your time, but @kubawerlos prepared this support with green pipeline in #7824, so it was merged before yours. Keep going with contributions 🙂.

**Comment by Chris53897** [comment]
@Wirone This is fine. Thanks @kubawerlos

**Pull request closed without merging**
