### PR TITLE
feature: `NullableTypeDeclarationForDefaultNullValue` - support for nullability in union types

### LINKED ISSUE #5785: Remove `|null` from union types when null is the default
I don't remember: do we have a rule to turn an argument like `?foo $bar = null` into `foo $bat = null`, don't we?
We might need one if not :)

And with union types, this rule should also turn `foo|bar|null $bar = null` into `foo|bar $bar = null`.

:pray:

### PR DESCRIPTION
**Pull request by HypeMC**
Fixes #5785 , ~depends on #5799 (**SHOULD BE MERGED FIRST**)~

~**UPDATE:** depends on #6210~

### CODE REVIEW

**Comment by julienfalque** [comment]
I think that `null` being implicitly allowed because of the default value can be misleasing, I always prefer when things are explicit.

**Comment by GrahamCampbell** [comment]
It wouldn't surprise me if there is an RFC in a few years to disallow implicit nulls in types. :P

**Comment by keradus** [comment]
Changing default config is BC BREAKER, let's keep the initial config in place.

Do we have a brave reviewer for this awesome PR, perhaps?

**Comment by Wirone** [comment]
@HypeMC any chance for a rebase? Also, I believe that it would be great to have an option for choosing nullable syntax applied to single type (related to #7002), otherwise we should set priorities and create integration test that would ensure final result is correct. I mean, if there's `Foo $foo = null`, this fixer should be able to convert it to `Foo|null $foo = null` or should be run before `nullable_type_declaration`, so it can fix `?Foo` if `union` syntax is chosen.

**Comment by HypeMC** [comment]
@Wirone Hi, yes, I was planning to check this out sometime this week. As for your second question, I think it'd make more sense to run this fixer before the `nullable_type_declaration` since there is (or will be once merged) a dedicated fixer for that.

**Comment by HypeMC** [comment]
@Wirone The PR has been rebased. I've also added support for DNF types since this wasn't initially covered because PHP 8.2 hadn't been released yet.

**Review by kubawerlos — CHANGES_REQUESTED** [review]
Needs priority test with `OrderedTypesFixer`.

**Comment by HypeMC** [comment]
> Needs priority test with `OrderedTypesFixer`.

@kubawerlos Done.

**Review by Wirone — CHANGES_REQUESTED** [review]
I don't understand why this PR keeps "DNF" notation everywhere, while it should focus on "union". DNF is a subset of union, because it's a union type where one or more alternatives is an intersection. `string|int|null` from the examples is NOT a DNF type, it's a regular union.

I really think descriptions and naming should be changed to better reflect what is supported.

**Comment by HypeMC** [comment]
> I don't understand why this PR keeps "DNF" notation everywhere, while it should focus on "union". DNF is a subset of union, because it's a union type where one or more alternatives is an intersection. `string|int|null` from the examples is NOT a DNF type, it's a regular union.
> 
> I really think descriptions and naming should be changed to better reflect what is supported.

@Wirone Works for me, done.

**Review by kubawerlos — APPROVED** [review]

**Review by Wirone — APPROVED** [review]
Great that you pointed out `ordered_types`, @kubawerlos 👍. LGTM 🚀!

**Comment by Wirone** [comment]
Thank you very much @HypeMC, great work 🍻!

**Pull request merged**
