### PR TITLE
bug: phpdoc_align must not fix 1+2+ spaces after comment star

### LINKED ISSUE #7048: phpdoc_align broken
### Description

Incorrectly de-indented doc.

```diff
     /**
      * @param array $parameters {
      *
-     *     @var string $order_by                    Return deployments ordered by id, iid, created_at, updated_at,
-     *                                              or ref fields (default is id)
-     *     @var string $sort                        Return deployments sorted in asc or desc order (default is desc)
-     * }
+     * @var string $order_by                    Return deployments ordered by id, iid, created_at, updated_at,
+     *             or ref fields (default is id)
+     * @var string $sort                        Return deployments sorted in asc or desc order (default is desc)
+     *             }
      */
```

### Runtime version

master branch 173db343ed768a722b9eb0968a1d0ed052a7475c

### Used command

```
php-cs-fixer --diff --dry-run -vvv fix
```

### PR DESCRIPTION
**Pull request by mvorisek**
fix #7048

replace #7049

### CODE REVIEW

**Comment by mvorisek** [comment]
Please push a test into my PR, I think the test will pass as long as there is one blank line after the 1st param (otherwise it is reindent as a `@param` comment as it always was, the whole support is a little hack).

**Comment by mvorisek** [comment]
@Wirone it took me several minutes to understand why a blank line in your example was not needed as I had written above (based on example from https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/issues/7048, ie. the current/original behaviour). You testcase was missing `<?php`...

Without the blank line, until nested declarations are supported natively by CS Fixer, the consequent comment should be indented as it is the main purpose of the fixer.

So this PR should be done and fix the reported problem.

**Comment by Wirone** [comment]
As I said, I am not even sure if it's a bug, since the whole `{}` scope for `@param` is invalid IMHO. I am not going to merge it without @kubawerlos and @keradus opinion on this. @mvorisek in terms of test case for nested scope - feel free to adjust or even remove it, I don't want it to be uncomfortable for you.

**Comment by mvorisek** [comment]
> As I said, I am not even sure if it's a bug, since the whole {} scope for @param is invalid IMHO.

IMHO it is not a bug too, however `phpdoc_align` can never parse comments "correctly" as the grammar could be any, even none :). In #7012 I improved the fixer to fix definitely more legit cases, but maybe too many for super edge cases - #6405. This PR, as coded now, should make everyone happy.

**Comment by kubawerlos** [comment]
So previously case like this:
```php
/**
 * @param array $goodIndent
 *    @param array $badIndent
 *                              @param array $veryBadIndent
 */
```
was fixed and after this change will be not?

**Comment by mvorisek** [comment]
I wanted to fix #7048, but with more sleep I think the issue is invalid as the "\@var inside \@var" will be parsed as 2 separate `\@var` by most tools, thus I belive my #7012 PR is correct and this PR, #7048 and #7049 should be closed as won't fix.

**Comment by GrahamCampbell** [comment]
What if we were to add an option to the fixer to allow it to run in a weaker mode to support this?

**Comment by mvorisek** [comment]
Feel free to reuse my PR. Only the change on l128 needs to be switchable.

**Comment by GrahamCampbell** [comment]
Sure. I am asking the question to determine if such a PR is likely to be accepted, before I do any further work.

**Comment by Wirone** [comment]
I believe we could merge it if logic was behind an opt-in configuration flag. Personally I think we shouldn't support invalid phpDoc by default, but for backward compatibility we could let people switch to weaker mode 🤔. 

But implementation should include 10% probability of fail, just to remind people from time to time they have invalid code. Just kidding 😉.

**Pull request closed without merging**
