### PR TITLE
feat: update `Symfony.trailing_comma_in_multiline` config

### PR DESCRIPTION
**Pull request by seb-jean**

### CODE REVIEW

**Comment by Wirone** [comment]
Hi @seb-jean, is this change approved by Symfony maintainers? Or maybe there's some conversation about it?

Anyway, as you can see it fails because we still support PHP 7.4 and trailing comma in function parameters' list is supported from 8.0 up.

**Comment by seb-jean** [comment]
This is to have the same value as https://github.com/symfony/symfony/blob/7.1/.php-cs-fixer.dist.php#L43

**Comment by Wirone** [comment]
But Symfony 7.1 requires a higher PHP version and can have this in local config, while it can't be added as-is to the ruleset in this repository because it's tested on 7.4-8.4.  You need to make conditional rules, adding `parameters` only for 8.0+.

@nicolas-grekas are you OK with this change?

**Comment by nicolas-grekas** [comment]
Yes, this changes makes sense (but I didn't think about the PHP-version issue - maybe "parameters" should be turned on only on PHP 8 that's what you mean?)

**Comment by Wirone** [comment]
Yes, exactly, it should be dynamic, based on PHP version. Thanks @nicolas-grekas for confirming 🙂.

@seb-jean are you going to make CI green?

**Comment by seb-jean** [comment]
I do not know how to do. Sorry.

**Comment by Wirone** [comment]
@seb-jean you should:

- modify ruleset in a way where `trailing_comma_in_multiline.elements.parameters` is added dynamically, if runtime's version is 8.0+ (this will fix `"parameters" option can only be enabled with PHP 8.0+.` in 7.4 jobs). So in `SymfonySet::getRules()`instead of returning array immediately you need to assign it to variable, use `'trailing_comma_in_multiline' => ['elements' => ['arrays', 'match']],` and then `$rules['trailing_comma_in_multiline']['elements'][] = 'parameters';` if PHP 8.0+, then return rules.
- run `composer cs:fix` which will apply the rule to the Fixer's codebase (as we use `@Symfony` ruleset as a base for `@PhpCsFixer` ruleset, so this change affects our code). In general you should be able to run `composer qa` without any error, then it's ready 😉.

**Pull request closed without merging**
